### ISSUE TITLE
[Push Notifications] Users moving to different timezones

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1043]
@orta @joeyAghion

Currently, Gravity geocodes a user’s location on every update of the user record in the DB. This means that if the user doesn’t make any changes but moves around the world, their timezone information will be incorrect and scheduling of push notifications will go wrong.

E.g. Ash moved from Amsterdam to New York, but his user record still states he’s in Amsterdam. Consequently, he received a push notification at 5am that he shouldn’t have gotten for another few hours.

Maybe we should have Gravity record the user’s location on each app launch or even activation? And would we send Gravity the device’s timezone setting or just some sort of ping and let Gravity geocode the IP address?

**Comment by orta** [comment]
>  some sort of ping and let Gravity geocode the IP address?

This was where I was thinking of going with this. @joeyAghion if we send a PATCH with no changes to the user, will that trigger the post-save lookup checks?

**Comment by alloy** [comment]
This would also be helpful to backfill the users that had the default New York time zone set from before Gravity automatically geocoded the user’s IP.

**Comment by joeyAghion** [comment]
I don't think Gravity geocodes on every update. I think it only does so when a user doesn't yet have a geocoded location. By design, we get the user's location on sign-up and geocode _that_, after which updates should not trigger further lookups. (We used to ask for location explicitly, but I don't see that anymore.)

I _don't_ think it makes sense to automatically update our internal knowledge of a user's location based on where they last accessed the API from. That could lead to surprising results. However, we already record a `last_sign_in_ip` and it would be reasonable to make it easier to match those to approximate locations. This would have to be done via server-side database rather than a lookup to an external API. We do something similar in Redshift already... not sure how awkward it might be to expose that to the push notification process.

**Comment by alloy** [comment]
> I don't think Gravity geocodes on every update. I think it only does so when a user doesn't yet have a geocoded location.

Ah yeah, you’re right: https://github.com/artsy/gravity/blob/97bcef6401259f47a3a83fdd5b677d6bae8116e7/app/models/domain/user.rb#L1041.

Triggering this would still solve the issue for those users that currently have the default time zone assigned (`nil`, which is New York).

> (We used to ask for location explicitly, but I don't see that anymore.)

https://www.artsy.net/profile/edit ?

> I _don't_ think it makes sense to automatically update our internal knowledge of a user's location based on where they last accessed the API from. That could lead to surprising results.

True. 

> However, we already record a last_sign_in_ip and it would be reasonable to make it easier to match those to approximate locations. This would have to be done via server-side database rather than a lookup to an external API. We do something similar in Redshift already... not sure how awkward it might be to expose that to the push notification process.

I’m not sure I understand how this would work and what good it would do us if we’re not really going to use it.

----

In any case, I’m now thinking that it might make the most sense for us to simple send the user’s timezone _as set on their phone_ on app launch. It is reasonable to assume that the OS info would be correct, even when automagically set by the OS, otherwise they’d have useless date/time info on their phones.

**Comment by ashkan18** [comment]
@joeyAghion with latest changes im making to geocoding i was thinking about actually updating the user's location each time `last_sign_in_ip` changes. What issues that can cause? It seems to me it makes sense to update the location if ip changes since that's how we originally set location. Right now we assume users location is where you accessed the API for the first time and never update it again, to me it seems updating each time would be more accurate.

**Comment by ashkan18** [comment]
I just talked to Matt, I didn't know user's can update their location here (https://www.artsy.net/collector/edit). Knowing that user's can set their location I agree it would be confusing to update their location based on their ip address changes.
