### ISSUE TITLE
Expanded lot info

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1116]
This information is available in markdown format, but will need to be retrieved from our (non-WebSocket) API. It should scroll, and the "close" button is "sticky" while the rest scrolls past it. @katarinabatina we wanted to verify the background of the "close" button would be white so it appeared separate from the content scrolling underneath it.

### Implementation Idea

Scroll view that is moved to cover the artwork when "Lot Info" button is pressed. Collapses on "Close" button tap. Markdown is downloaded from the API, rendered, and placed in a scroll view. 

### Estimate

1 Day

**Comment by katarinabatina** [comment]
@ashfurrow in order to simplify, lets offset the close and data 
![image](https://cloud.githubusercontent.com/assets/6482926/12794916/7fa46dbe-ca85-11e5-81d0-71e09bbf9b42.png)

so that the content can just scroll beneath
https://s3.amazonaws.com/f.cl.ly/items/0Z1K3h0L1F3Z221c2N0k/Screen%20Recording%202016-02-03%20at%2002.52%20PM.gif?v=7dbbf17e

**Comment by ashfurrow** [comment]
Makes sense to me!

**Comment by orta** [comment]
OK, this currently does everything but supporting the close button staying at the top, and is just waiting on figuring out how to get the extra data in there

**Comment by katarinabatina** [comment]
👍
