### ISSUE TITLE
HeaderModule

### ISSUE THREAD

**Issue by briansw** [artsy/eigen#1132]
![header-module](https://cloud.githubusercontent.com/assets/1022172/12961124/df25247c-d00c-11e5-8b8e-40f84d04e6af.png)

**Comment by katarinabatina** [comment]
Follow button states:

User follows the artist and the state changes from follow to following, if the user choose to immediate unfollow, the reverse animation occurs:
![firstfollow](https://cloud.githubusercontent.com/assets/6482926/14755465/7a0205e2-08b0-11e6-8f95-294295cac767.gif)
 
Once the  user leaves the artist view, the next time they encounter the follow button for the artist it should look like Brian specified, grayed out. Below shows what happens when a user decides to unfollow an artist they are currently following:
![secondunfollow](https://cloud.githubusercontent.com/assets/6482926/14755493/ac1a1cd6-08b0-11e6-8dd0-89e1361c3b21.gif)

**Comment by alloy** [comment]
I made a mistake while implementing the follow button. Based on previous behaviour, [the ‘INVERTED BUTTON’ in the style guide](https://www.artsy.net/style-guide/buttons), and @katarinabatina’s new design that animates to purple, I assumed the selected state would be purple, but I now notice it’s greyed out.

I’m delaying on fixing this at least for the 1st beta and until I hear back from you what the final word is on the design.

(Note that the current version does not animate yet, I’m delaying that until we do work on the home view.)

**Comment by briansw** [comment]
@alloy sounds good. @katarinabatina's designs above is the one we'd like to implement:

- When user initially follows: animate to purple and stay purple
- When user lands on a view where they're already following the artist, gallery, etc the button should be grayed out

**Comment by alloy** [comment]
> * When user lands on a view where they're already following the artist, gallery, etc the button should be grayed out

@briansw Interesting, why that difference in behaviour?

**Comment by alloy** [comment]
This is done in v1 of Emission.
