### ISSUE TITLE
[Analytics] Events around auctions

### ISSUE THREAD

**Issue by anipetrov** [artsy/eigen#1289]
## Tracks

- [x] **Tapped "Register to bid"**: fired anytime user taps the "Register to bid" button. This button is currently available on an auction sale page screen (for both preview and open auctions) AND on the sale information screen (for open auctions)
  * properties: {auction_slug, auction_state: [open, preview], context_type: [live, [auction sale page](http://cl.ly/1X1G171t3z1P), [sale information](http://cl.ly/3T1t3a3U2T1R)]}

- [x] **Bid button**: note this is already implemented, so this is more of a QA item. Event should be firen anytime a bid button is tapped. As far as I know, the only way to access this is through the artwork page currently. Putting in context_type property to be future-proof.
  * properties: {artwork_slug, auction_slug, context_type: [artwork page]}

- [x] **Tapped artworks "Refine"**: fired upon tapping the "Refine" button on the auction sale page lot section; [screenshot](http://cl.ly/0D411o2b0o1j)
  * properties: {auction_slug, auction_state: [open, preview]}

- [x] **Tapped auction "Contact"**: fired upon tapping the "Contact" button on the sale information screen; [screenshot](http://cl.ly/1b0U2L03370z)
    * properties: {auction_slug, auction_state: [open, preview]}

- [x] **Tapped "Apply" refine**: fired upon tapping "Apply" button on the refine screen; [screenshot](http://cl.ly/002y1p2B2K2k)
 * properties: {context_screen: [auction slug, gene page slug, etc.]}

## Screens
- [x] **Sale**:
  * properties: {auction_slug, slug}

- [x] **Sale information**: [screenshot](http://cl.ly/34372M402l0l)
  * properties: {auction_slug, slug}
- [x] **Refine**: [screenshot](http://cl.ly/0236301H2r3y)
 * properties: {context_screen: [auction slug, gene page slug, etc.]}

cc @katarinabatina @devangt

**Comment by katarinabatina** [comment]
@orta @ashfurrow needs to be in before we ship new auction view

**Comment by orta** [comment]
@anipetrov this will be in the next beta - maybe today

**Comment by katarinabatina** [comment]
@alloy @ashfurrow @anipetrov we're submitting today lets test and close this issue

**Comment by anipetrov** [comment]
## Tracks

- [ ] **Tapped "Register to bid"**: Fires correctly, however when I tap "register to bid" from the sale information screen, I get the event with property `context_type = sale` and it should be `context_type = sale information` instead. 

- [x] **Bid button**: fires correctly with all desired properties

- [ ] **Tapped artworks "Refine"**: this is currently named `Tapped Auction Refine`. I think we should stick to calling it `Tapped Artworks Refine` and propertirize to specify whether it's coming from an auction or another context. It does fire correctly.

- [ ] **Tapped auction "Contact"**: did not see this fire but it could be because the visualizer doesnt register it (since tapping contact takes you to email)

- [ ] **Tapped "Apply" refine**:  don't see this firing 

## Screens
- [x] **Sale**: I see a screen view but it is not called `Sale`. That would be fine by me.
![image](https://cloud.githubusercontent.com/assets/8701687/13959096/00b90900-f029-11e5-8829-6364c62f1c5b.png)

- [ ] **Sale information**: did not see this fire but it could be because the visualizer doesnt register it (since a modal pops up)

- [ ] **Refine**: did not see this fire but it could be because the visualizer doesnt register it (since a modal pops up)

cc @katarinabatina @alloy

**Comment by katarinabatina** [comment]
@orta do you have most familiarity here?

**Comment by orta** [comment]
Will give it a quick lint

**Comment by orta** [comment]
Working through this list:

- [x] **Tapped "Register to bid"**: Fires correctly, however when I tap "register to bid" from the sale information screen, I get the event with property `context_type = sale` and it should be `context_type = sale information` instead. 

- [x] **Bid button**: fires correctly with all desired properties

- [x] **Tapped artworks "Refine"**: this is currently named `Tapped Auction Refine`. I think we should stick to calling it `Tapped Artworks Refine` and propertirize to specify whether it's coming from an auction or another context. It does fire correctly. It does carry `auction_slug` now 

- [ ] **Tapped auction "Contact"**: did not see this fire but it could be because the visualizer doesnt register it (since tapping contact takes you to email)

- [ ] **Tapped "Apply" refine**:  don't see this firing 

## Screens
- [x] **Sale**: I see a screen view but it is not called `Sale`. That would be fine by me.
![image](https://cloud.githubusercontent.com/assets/8701687/13959096/00b90900-f029-11e5-8829-6364c62f1c5b.png)

- [ ] **Sale information**: did not see this fire but it could be because the visualizer doesnt register it (since a modal pops up)

- [ ] **Refine**: did not see this fire but it could be because the visualizer doesnt register it (since a modal pops up)

cc @katarinabatina @alloy @ashfurrow
