### ISSUE TITLE
Recommendation Module: Onboarding Update 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1321]
![image](https://cloud.githubusercontent.com/assets/6482926/13907387/5ba9ba88-eec3-11e5-9646-8ad35351b209.png)

**Comment by alloy** [comment]
Since 2.4.0 we have also been keeping track of all the artists/artworks/categories a trial user visits in a local cache file, we can use that data to improve suggestions.

1. Need to determine what the best way is to do that. E.g. sorts artists by number of artworks viewed of that artist?
2. The code that does the collection of that data needs to be removed once the new on-boarding is released.
