### ISSUE TITLE
Wrong works show up under For Sale

### ISSUE THREAD

**Issue by robertlenne** [artsy/eigen#133]
Compare:

![image](https://cloud.githubusercontent.com/assets/566531/6093097/9a14ebe4-aec8-11e4-8f38-da167f9d8724.png)

And: 

![image](https://cloud.githubusercontent.com/assets/566531/6093100/a469e694-aec8-11e4-8e0d-59c0a1679fe2.png)

**Comment by katarinabatina** [comment]
@alloy realized this wasn't added to the milestone, completely my bad. Wanted to know if this was a simple, api re-route kind of a bug or something more significant?

**Comment by alloy** [comment]
@katarinabatina I’ll have a look.

**Comment by alloy** [comment]
Documenting for myself:

1. On first load of the `ARArtistViewController` there are no artworks for sale loaded yet.
2. When selecting the ‘for sale’ tab, [this branch](https://github.com/artsy/eigen/blob/8f18c61f3af994e2fbf1e68fa83a3a4612a4603b/Artsy/Classes/View%20Controllers/ARArtistViewController.m#L354) gets hit, which leaves the ‘all artworks’ set loaded in the `artworkVC`.
3. Then after [fetching more artworks](https://github.com/artsy/eigen/blob/8f18c61f3af994e2fbf1e68fa83a3a4612a4603b/Artsy/Classes/View%20Controllers/ARArtistViewController.m#L357) it [adds the ‘for sale’ artworks to the `artworkVC`](https://github.com/artsy/eigen/blob/8f18c61f3af994e2fbf1e68fa83a3a4612a4603b/Artsy/Classes/View%20Controllers/ARArtistViewController.m#L422) which was still holding the ‘all artworks’ set and thus the ‘for sale’ artworks get appended to the end of those.
5. Switching back to the ‘all artworks’ tab and then to the ‘for sale’ tab will show only the ‘for sale’ artworks because at this time they have already been fetched.
