### ISSUE TITLE
Deprecate Trial User: Onboarding Update

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1330]
We want to "kick out" trial users to see the splash screen, take them through onboarding, and ask them to make an account. Will discuss how we can use the passive data we've been collecting on them in a different story

**Comment by mennenia** [comment]
Relevant tasks to deprecating trial user: https://github.com/artsy/eigen/issues/1321#issuecomment-199253014

**Comment by mennenia** [comment]
I've removed the trial user from the initial launch of the app, so if you don't have an account, you will go through onboarding. 

@alloy @katarinabatina:
- Have we decided what to do with the gathered data? 
- Shall I remove _all code_ that relates to the trial user? 
- Would there be a case where we'd lose data or somehow cause problems for them that you can think of?

Just want to clarify / be sure :). Thanks!

**Comment by alloy** [comment]
> * Have we decided what to do with the gathered data?

You mean the trial user analytics data we started collecting locally recently, right? I don’t believe we’re going to use it, but I’ll defer to @katarinabatina on that.

> * Shall I remove all code that relates to the trial user?

Yes, remove all code related to trial users.

> * Would there be a case where we'd lose data or somehow cause problems for them that you can think of?

We just need to be sure that we still include the trial user UUID, which we generated on the device, is included in analytics data, at least at first, so that previous trial users can be correlated to signed-up users.
