### ISSUE TITLE
type formatting on auction sale overview

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1341]
We're using Garamond Bold when we should be using Garamond Semi-bold

![image](https://cloud.githubusercontent.com/assets/6482926/13958845/08f28d54-f028-11e5-9066-3aec1a293a06.png)

![image](https://cloud.githubusercontent.com/assets/6482926/13958858/0dcca6fc-f028-11e5-8517-9e7d73d4ac50.png)

**Comment by ashfurrow** [comment]
Looks like this is a cause of parsing markdown into `NSAttributedString`. We're not specifying any font beyond "Garamond", and because the markdown string includes bold text, it goes to Garamond Bold instead of semi-bold. 

An approach could be to modify `ARTextView` at [this](https://github.com/artsy/eigen/blob/cba98db60b034a032fd0eec2327d4138598a34d4/Artsy/Views/Styled_Subclasses/ARTextView.m#L145) point to look for uses of bold and change to semi-bold instead. It's a pretty brute-force technique, and we'd need to limit it to cases where we need it (to avoid changing formatting throughout the app). @alloy if you have an alternative idea, I'd love to chat.

**Comment by alloy** [comment]
@ash The question is if headings anywhere in the app should use semi-bold, but as a way to control this, what about adding an optional attributes argument to the initialiser of ARTextView?

**Comment by ashfurrow** [comment]
Definitely can do that, make it "opt-in" so to speak. If that sounds good, I'll start implementing.

**Comment by alloy** [comment]
Aye 👍
