### ISSUE TITLE
How do we know who has push enabled and who doesn't? 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1446]
I want to know how we determine which users have push enabled and which don't and how we can get this data into redshift. 

I'd like to use this data to...
...Determine what kind of prompts to serve users who don't have them enabled
...Evaluate the success of changing how we ask for notification permissions
...Evaluate the effects of increasing push on the rate at which users turn off their notifications

cc: @alloy @anipetrov

**Comment by alloy** [comment]
We currently determine what user’s have push enabled simply by whether or not Eigen reported a device token to Gravity, which only happens when a user allows notifications.

We should be able to determine the up-to-date settings at any time. Theoretically the user can go to the Settings app and disable notifications at any time, so if we want to have as current as possible information, we should report whether or not notifications are allowed on each activation of the app.

**Comment by katarinabatina** [comment]
@anipetrov do you think it's feasible that we could have "events" (?) for the notification status in redshift?
