### ISSUE TITLE
[Onboarding] Optimal way of retrieving related artist 

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1449]
![loop](https://cloud.githubusercontent.com/assets/373860/14710569/c975de2a-07cd-11e6-91e0-944af3f1f0ee.GIF)

We're currently working on a new onboarding flow, which contains artist and category search, it works roughly like so:

* You follow the artist "Damien Hirst".
* You get back a list of related artists.
* You follow the artist "Gavin Turk", which needs to be replaced with another related artist, e.g. "Garry Hume".

As can be seen in the GIF, there are currently 2 problems with this:

1. The user should not see a suggestion for an artist that is already in the list of suggestions, e.g. "Garry Hume".
2. The user should not see a suggestion for an artist they already decided to follow, e.g. "Dinos Chapman".

To solve this, we should be able to pass a list of IDs to the related artists/categories endpoints that specifies entities that should _not_ be included. E.g.:

`GET /api/v1/related/artists?artist[]=gavin-turk&exclude[]=garry-hume&exclude[]=dinos-chapman`

Finally, I'm wondering if the related artists/categories endpoint would be able to keep offering suggestions, even if, based on the exclude list, the link between the followed entity and the suggested one would be very weak?

**Comment by mzikherman** [comment]
You can use https://github.com/artsy/gravity/blob/master/app/api/v1/me_suggestions_endpoint.rb#L39-L60 , this is what powers the 'follow' widget:

![screen shot 2016-04-21 at 12 30 15 pm](https://cloud.githubusercontent.com/assets/1457859/14716854/d1f54286-07bc-11e6-8a6e-39c6431eaf38.png)

It returns related artists for a given artist, and can exclude artists that you already follow.

**Comment by mennenia** [comment]
Cheers!

Unfortunately we can't use that API. On iOS the onboarding happens before sign up, so we haven't created a user yet.

**Comment by mzikherman** [comment]
Hmm, that seems odd to me. How is a user able to click 'Follow' on multiple artists (in the GIF above) if they are not actually a user?

**Comment by mennenia** [comment]
We store the IDs locally, and then once the user signs in we send all the follow requests. 

Some insight into the onboarding flow:

<img width="1251" alt="29539dce-f1d4-11e5-8d36-982d872ce787" src="https://cloud.githubusercontent.com/assets/373860/14717753/cf7e95a6-07ea-11e6-9f3e-816d7e57cf8e.png">

**Comment by alloy** [comment]
@mzikherman The idea to not first create a user is _probably_ meant to not scare the user away by immediately showing a sign-up screen (@katarinabatina correct me if I’m wrong). Eigen will require sign-up in the future, so we really don’t want users to be scared away too soon.

**Comment by mzikherman** [comment]
ooo interesting, ok! I see in that flow diagram that the 'follow artists' step is prior to 'sign up & join' step, so it seems that local storing of 'pending' follows is necessary.

In that case, it does seem like an `exclude_ids` param can/should be added, with an alternative being a total client-side solution, where Eigen makes requests for 'related/suggested artists', and filters out duplicates.

I'm into the idea of adding `exclude_ids` upstream to the API, I think that seems reasonable.

> Finally, I'm wondering if the related artists/categories endpoint would be able to keep offering suggestions, even if, based on the exclude list, the link between the followed entity and the suggested one would be very weak?

The API already returns the similar artists sorted by a decreasing similarity 'score', so a request with the exclusion parameter may return an empty list, whereas w/o that parameter would return a list of artists. So yes is the answer to that question!

Also, since we're on this already, I think instead of `/related/artists`, we should use `/me/suggested/artists`. The intent of the `/me/suggested` namespace is to house...well...suggestions!, so it might be better to use that (even though right now in this specific case, `/related/artists` and `/me/suggestions/artists` are basically equivalent, except for the logged-in requirement)

So, I think we should add `exclude_ids` support to the API, and we should use `/me/suggested/artists` over `/related/artists` in this context (and I'll make a PR to relax the logged-in requirement for that endpoint).

Let me know what you think! @mennenia @alloy

**Comment by mennenia** [comment]
Thanks for the response!

> with an alternative being a total client-side solution, where Eigen makes requests for 'related/suggested artists', and filters out duplicates

We considered this, but would rather not because we'd like to:

* Be able to make a request for a single suggestion (`size=1`), to limit amount of network data.
* Not have to make multiple requests, which would be a possibility if after filtering out dupes there were no suggestions left.

On a similar note, [when testing the `size` pagination parameter](https://stagingapi.artsy.net/api/v1/related/artists?artist=marina-abramovic-1&size=1), it didn't seem to respect that input, returning the full list. Could you check to see if it's working? We'd love to limit our fetch to just one suggestion. 

> so a request with the exclusion parameter may return an empty list, whereas w/o that parameter would return a list of artists. So yes is the answer to that question!

Noted. We'll remove the row if there are no more suggestions. 

> Also, since we're on this already, I think instead of `/related/artists`, we should use `/me/suggested/artists`. The intent of the `/me/suggested` namespace is to house...well...suggestions!
> […]
> I'll make a PR to […] relax the logged-in requirement on the endpoint.

The reason why we were not looking at any of the `/me/*` endpoints, is that we don't have a user account at that time yet, so the API can't really make any personalised suggestions. So based on 'given 1 artist, give me related ones', the `/related/artists` API seems more appropriate.

But if you think that adding it to the `/me/suggested/artists` endpoint definitely makes more sense for other reasons, I'd love to know!

**Comment by mzikherman** [comment]
Yes, philosophically `/me` does not need to require a logged-in user. We have some `/me` endpoints that are like this. Technically....everyone is an Artsy user, some just haven't signed up yet :)

I think `/me/suggestions` are more appropriate to use in onboarding/suggestions (and allows us to change that endpoint, while leaving alone the `/related/artists` one). Since in this context, it seems like the use case is to present artist suggestions to follow to 'a' user (whether or not that person winds up becoming a signed-up user is immaterial or not), so I think `/me/suggestions` is appropriate. Consider that the mobile client can use it with a signed-out user to receive more generic suggestions, while web clients can use it with a logged-in user to receive more personalized suggestions.

**Comment by mennenia** [comment]
If that is the endpoint you'd prefer us to use I'm happy to call `/me/suggestions` instead. Also, pagination parameters work for `/me/suggestions`, yay. 

I personally think the API doesn't make it particularly clear that this would be the preferred end point for a non user to look for suggestions, but sure. Out of curiosity - what other `/me` endpoints can be used without a logged in user? 

Lastly, we are doing the same for categories. Will this also work for genes / categories, @mzikherman?

**Comment by alloy** [comment]
@mennenia Is this all done with #1822?

**Comment by mennenia** [comment]
Yeah.. I thought it would auto close! Doing so now.
