### ISSUE TITLE
Timeout on pod install

### ISSUE THREAD

**Issue by tabuchid** [artsy/eigen#1543]
I noticed you guys are experiencing the same timeouts on `pod install` that we are. Is that a github issue or ...?

**Comment by orta** [comment]
Not to my knowledge? 

Have you switched to 1.0 and are cloning the full repo due to [Specs Repo changes](https://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem) - about deep cloning?

Our rationale for checking in Pods is so that we can rely on historical versions, and so that they also receive code review: https://github.com/artsy/eigen/commit/b827a762cc3da9687d88d819e9f84ab992d7d4de

**Comment by tabuchid** [comment]
Yeah, we are now on 1.0. Where I've seen the issue is on CCI builds. This one of yours had the same problem I've seen. https://circleci.com/gh/artsy/eigen/2576

**Comment by alloy** [comment]
@orta Do you know why it’s doing a full setup btw? `Setting up CocoaPods master repo`

**Comment by orta** [comment]
We're not doing anything which should force it to get wiped, perhaps their mac instances default to not having a `~/.cocoapods/repos`  - which could make sense if they're trying to keep the image size down. 

Realistically, this issue, https://github.com/CocoaPods/CocoaPods/issues/5009 would probably need to be addressed to decide what the best idea for CI sources is WRT keeping up their repo

**Comment by szweier** [comment]
According to their docs CircleCI is keeping around the directory used by Cocoapods. https://circleci.com/docs/how-cache-works/

**Comment by alloy** [comment]
Seems like this was a temporary issue, let me know if there’s still something actionable.
