### ISSUE TITLE
Handle lots re-ordering according to the operator

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1547]
An operator could change a lot from say the 2nd lot, to the 4th index, this totally throws off all our distance from lot calculations ( and whether a lot is open or closed. )

Word is, it regularly happens that you go back to existing lots too.

**Comment by ashfurrow** [comment]
I've taken a look, and it appears as though we're only using distances in `distanceFromCurrentLot` for the toolbar's "X Lots Away" UI. I built the lot list to handle out-of-order _opening_ of lots, and the lot set VC too. The open and closed lots don't need to be contiguous, they can be split up okay.

The problem would be if the lot numbers no longer apply to the lot indices. I don't think the lot _numbers_ change often (since they're printed on artwork info cards, preview magazines, etc) I can see the auction partner wanting to list lots in "2,1,3" order. That'll be a little tricky. A stopgap for v1 would be to keep them in 1,2,3 but open them in whatever order they want, which we do support already. Thoughts?

**Comment by devangt** [comment]
This is currently supported. But the lots away becomes "-ve"

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
