### ISSUE TITLE
[Live] Show indeterminate loader until we've connected to causality

### ISSUE THREAD

**Issue by orta** [artsy/eigen#1633]
Currently it waits for just metaphysics data.

**Comment by katarinabatina** [comment]
when live UI is first opened I often am faced with this state
![image](https://cloud.githubusercontent.com/assets/6482926/16066447/57ad9024-3281-11e6-9556-c9197fa238e2.png)


wondering if we can show this while we fetch the data
![image](https://cloud.githubusercontent.com/assets/6482926/16066513/dcefe354-3281-11e6-8ee6-42cd6a2f98ef.png)

**Comment by ashfurrow** [comment]
I think an initial stab at this could simply extend the existing indeterminate loading animation until the lot state callback from causality comes through.

**Comment by acjay** [comment]
Part of the problem is that for large sales, Causality is currently retrieving and sending ALL the data for every lot. This is a long operation. I'm looking into sending an initial state in the same shape as what we currently send, but excluding information from upcoming lots. I don't _think_ we'll be able to fix this on day 1, so there are just going to be long waits. I'm a bit nervous about how this is going to hold up if many users join the sale at a similar time.

**Comment by orta** [comment]
What I wanted to pitch, but never got around to was that we could have a spinner on the lower half of the screen, and allow people to scroll through the lots, but still feel like work was happening. It can take a long time to connect

**Comment by ashfurrow** [comment]
This is trickier than just waiting for causality to connect because we don't allow the user to cancel the live interface with the existing design, and lengthening that un-cancellable state while we try to connect to causality forever doesn't feel right. I'm growing more convinced that to do this at all, we can't re-use any existing infrastructure, and write a new purpose-built "loading" screen.

**Comment by acjay** [comment]
What data does Eigen need per lot to load the initial screen?

The plan in the medium-term is to have Causality deliver a subset of lots in `fullLotStateById` (like perhaps just the first lot), and then clients would request additional lot data at their leisure with an explicit command. In a perfect world, clients don't need anything from `FullLotState` (see below) until we actually navigate to the lot. This would be great, because it would greatly reduce the amount of querying Causality needs to do to prepare `InitialFullSaleState`, as well as the network load and JSON (de)serialization time.

But I'm also working on changes to reduce the amount of database queries Causality makes, which should hopefully remove the possibility that we're I/O bound at the Causality <-> Postgres link up, which may be the case right now.

It seems unlikely we'll be able to do all of this in time for this first release, though :(

```
  case class FullLotState(
    events:            Map[String, StoredLotEvent],
    fullEventOrder:    Seq[String],
    eventHistory:      PastEvents, // TODO deprecated, remove when clients are compatible
    derivedLotState:   DerivedLotState,
    incrementPolicyId: Option[String],
    currentIncrement:  CurrentIncrement
  )
```

**Comment by katarinabatina** [comment]
@ashfurrow we can add an cancel button to mitigate that

**Comment by ashfurrow** [comment]
@acjay agreed, when we have the chance, the two of us should sit down with @sweir27 and figure out a more on-demand socket protocol.

@katarinabatina cool, I'll send a screenshot in the PR so you can see what it looks like.

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
