### ISSUE TITLE
Bid History and Bid State Regression

### ISSUE THREAD

**Issue by devangt** [artsy/eigen#1651]
On Latest builds the history and bid button states have regressed

- Bidding seems to work
![image](https://cloud.githubusercontent.com/assets/753098/15895333/b15476f2-2d58-11e6-8947-3e15a43e9199.png)

- Gets me to Bid Sent State
![image](https://cloud.githubusercontent.com/assets/753098/15895343/bd84dcf0-2d58-11e6-98d9-8b28cdba1ca8.png)

But no history or bid button states are reflected.

**Comment by orta** [comment]
When I looked this briefly, it feels like we're not registering a that there's current lot going on.

**Comment by orta** [comment]
It looks like causality isn't sending down a `currentLotId` in the initial state anymore:

``` JSON
 "type" : "InitialFullSaleState",
  "currentLotId" : null,
  "lotsWatched" : [
```

@acjay know anything that might have changed this?

**Comment by acjay** [comment]
I think I know what's going on. With the change made in https://github.com/artsy/causality/pull/194, absent values are being serialized as `null` instead of being omitted from the JSON, to be more explicit about what the fields are. I should have realized this might impact decoders that differentiate between those two cases. In your decoding, is this an easy change? If not, might make sense to unroll that change in Causality, but it will break Gravity sync temporarily.

I believe you were previously already handling the omission of that value by defaulting to the first lot in Metaphysics order.

**Comment by orta** [comment]
Interesting, we should be exhibiting the same behavior in both cases before & after.

This is the key parsing part

``` swift
let currentLotID = state["currentLotId"] as? String
```

Which would be nil if it wasn't present, and when it's not a string. I'll chat with @ashfurrow when he's back about it 👍

**Comment by acjay** [comment]
Hmm. Yeah, before and after the JSON change, it was possible for `currentLotId` to not contain an ID. It has to be set by the operator, since Causality doesn't know the lot order, which is the fallback should be to assume the first `sale_artwork` in Metaphysics is the current lot when none is set.

**Comment by ashfurrow** [comment]
It sounds like the current lot isn't being set on a fresh sale, until the first lot is sold/passed and the next one is open. This could be prediction-related?

**Comment by ashfurrow** [comment]
What I mean to say is, whether a json key was ommitted or null, our behaviour is consistent. The bug appears to be caused by the `currentLotId` being empty/null when it shouldn't be, which could be caused by prediction or our Jenkins job to create an auction.

**Comment by acjay** [comment]
(+ @sweir27) Yeah, I don't believe we currently have a trigger in place to set that first lot, it only happens when the lots change over. But the operator doesn't necessarily take any actions between when the last lot was added to the sale and they open the first lot in the Prediction operator interface. So, I'm not sure what the ideal event would be to act as the trigger for the initial setting of the current lot. If it's possible, I think it would be simplest for clients to fall back to Metaphysics ordering.

**Comment by sweir27** [comment]
Yeah it's tricky because from gravity's perspective, probably the sale is created and then lots are added so we can't pass `currentLotId` in the causality sync there. Right now in prediction we set it in the `sync-auction` script, but also fall back to the first lot from metaphysics. I think that's the move for eigen as well.

**Comment by acjay** [comment]
We're growing a suite of Gravity model change listeners that sync data to Causality. Eventually, we can probably do something that updates `currentLotId` whenever the ordering is changed, but that won't be available in the short-term.

**Comment by ashfurrow** [comment]
I don't think I've explained myself clearly; this regression from eigen exists only on the first lot, subsequently opened lots work fine. I believe a solution would be for prediction to set the current lot when it opens a lot, instead of only when switching lots.

**Comment by acjay** [comment]
But that wouldn't solve the problem before the first lot is opened, when the operator is waiting for the auctioneer to begin. This would be the time period between `live_start_at` (which in Force/MG at least makes Prediction available) and whenever the first lot actually goes on block. Sorry if I'm misunderstanding, but is there a reason we can't fall back to the first lot in the `sale_artworks` order?

**Comment by ashfurrow** [comment]
It would; the jump to current lot button would be missing because there is no current lot, and the bid history would be empty because the lot isn't open. The screenshot from Devang above only looks bad if the lot is open, if isn't (because we're in the time period you mention) then this would be what I expect, right?

**Comment by ashfurrow** [comment]
Is there a use case to have prediction open the first lot without setting it to the current lot?

**Comment by acjay** [comment]
Ahhhhh. I thought something was crashing. Should have looked more closely at the ticket. I think the only problem is that the lot should be in the max bidding state, since it's upcoming.

**Comment by acjay** [comment]
So basically, the bidding UI is contingent on whether the lot is Open (max bidding available) or OnBlock (first-price bidding). But not necessarily on whether it's the current lot.

**Comment by acjay** [comment]
But yeah, I think we do also want have the operator interface set the current lot when a lot is opened. That way, the navigation back to the current lot will work for sure on the first lot, as Ash mentioned.

**Comment by devangt** [comment]
Moving to QA as per Triage

**Comment by devangt** [comment]
Verified
