### ISSUE TITLE
Live: Bid history should not by default show most recent event

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1696]
currently if a new event comes in from the floor that is lagging behind the online action, then a bid event comes through that is no longer relevant 

![image](https://cloud.githubusercontent.com/assets/6482926/15979080/e6a8c5d2-2f2f-11e6-9dd1-6303bf29ac3e.png)

in this scenario there was a crazy bidding war online, the auctioneer took a floor bid and that was published on the top of the list, it should slot in, at the relevant position 

see web
![image](https://cloud.githubusercontent.com/assets/6482926/15979111/0b64e860-2f30-11e6-9d79-09af3f0cb0e3.png)

**Comment by ashfurrow** [comment]
I'll have to see how prediction is ordering these, but this will likely be a very large change. @sweir27 can you comment on prediction's ordering?

**Comment by devangt** [comment]
Really bad but not show stopper. We can try to get it in.

**Comment by katarinabatina** [comment]
It's pretty disorienting to see a stream of bids come in at a value that is less than what I'm being currently asked to bid. I could imagine someone thinking we're duping them into bidding more than the actual value of the work. I would reconsider if this was a show stopper or not. @devang

**Comment by ashfurrow** [comment]
This should be incidentally fixed by Orta's work on https://github.com/artsy/eigen/issues/1695

**Comment by devangt** [comment]
This was gnarly one to triage. Glad it is getting fixed with #1695 . 

We kept this in the Critical bucket for the longest and only removed show stopper because of the following reasons:
- The events coming in were true events
- User could discover the state of bid by scrolling.
- If it was unclear to someone and they called us it would be an easy (albeit a little embarrassing) conversation to point them there.

**Comment by devangt** [comment]
done for now. Individual updates will be tackled with new issues/epics
