### ISSUE TITLE
Create Demo Account

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1769]
If we deprecate the trial user (as intended and discussed here: #1330), we will run into the issue that one would not be able to use the artsy app to test/play without creating an account. This could happen for instance at Apple Stores, when we've been installed on hardware there. 

**Options:**
- Keep trial user
- Create demo accounts to be used
- ...? 

**Keeping trial user:**
I believe this would not be the best way forward, as:
- All of the upcoming features revolve around users having followed certain content. Designing / developing for this edge case will undoubtably lead to bugs or things not considered.
- In the case of Apple demos, they are also making it more of a requirement to have users login, so I would assume that they would have their own demo accounts or some kind of support to show users exciting apps and content in stores.

**Creating Artsy demo accounts to be used:**
We could just have pre-defined accounts, with some follows etc tied to it, and give it to people who want to trial Artsy. Something to consider perhaps when logging into such an account, is pulling data in and not syncing back as otherwise the account could become cluttered.

The interface to this could be as sophisticated as having a nice UI for it, or as simple and naff as giving people a post-it with login credentials.

@alloy, @orta, @katarinabatina, thoughts?

**Comment by alloy** [comment]
I agree that I would prefer a ‘real’ demo user account so that in general the app doesn’t need to know about these details.

I wonder if it would be simple to include a single hardcoded place in the API layer where we check if the account is the demo one and then simply don’t perform POST/PUT requests.

**Comment by orta** [comment]
Think we log in with a pre-defined account, then continue to use [the alert](https://github.com/artsy/eigen/blob/master/Artsy/View_Controllers/Util/ARTrialController.m#L64) for ":not available in the demo" on anything that would constitute a change on that user account, the demo rules stipulate that it should wipe all state between launches if I recall.

**Comment by mennenia** [comment]
Ok, in which case, the quickest starting point here would be keep the current code as it supports demo mode already, just remove any access points to it from onboarding or elsewhere in the app.

Sound good?

**Comment by alloy** [comment]
My preference would be the following:

* We still have a separate build for demo purposes.
* Instead of [this](https://github.com/artsy/eigen/blob/818ebbdfe0b48a28a6a973fc3232a7ea7823b665/Artsy/Constants/ARAppConstants.m#L28-L32) and checking for it in various places, we hardcode the (_real_) demo user account.
* There will be no need for on-boarding, as the user should already be signed in on each launch.
* At the lowest networking abstraction level, we block any mutating HTTP verbs (`POST`/`PUT`/`DELETE`/`PATCH`) if the user is the demo account one and show an alert that says “This action is not available in the demo.”

Cons:

* We can delete any code related to ‘trial’ mode.
* We can delete a bunch of ‘demo’ mode conditionals.
* We don’t have to think of ‘demo’ mode conditionals anymore in the future.
* People trying the demo app get a real experience of what the app would look like, including e.g. a rich personalised home view.
* We (at Artsy) can update the demo account’s profile by following/saving new artists/works etc.

**Comment by mennenia** [comment]
Trial Users are being removed #1831.
