### ISSUE TITLE
Received push notification at wrong time.

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1778]
I received a push notification for Phillips opening an hour after it opened, so did Chloe and Dylan. Should get help from @anipetrov later to examine Looker analytics logs to verify it's not a fluke or something related to outdated APNS identifiers.

**Comment by mennenia** [comment]
Were they only for those who register to bid? I didn't register, and I didn't receive a push notification :).

**Comment by alloy** [comment]
@mennenia You would receive a notification if you’ve ever registered for any auction.

**Comment by mennenia** [comment]
Cool, in which case, ignore me not receiving a push.

**Comment by alloy** [comment]
To add to @ashfurrow’s information, I _believe_ (with a high certainty) that I received the notification at the right time, however I only glanced at it.

**Comment by anipetrov** [comment]
Could it be related to the fact that New York is GMT/UTC - 5h during Standard Time and GMT/UTC - 4h during Daylight Saving Time or our timezone conversion takes care of that?

**Comment by alloy** [comment]
Ooookkkkkkkaaaayyyyy, so @alloy properly woke up a few days later…

The issue is actually really simple and obvious. The Live Auction opening notification is sent using the  [_from_ option](https://github.com/artsy/gravity/blob/b57aae7f42f33243ab64381d14b0f85649f12351/app/services/push_notification_service/scheduler/collector_experience_and_gmv.rb#L137) with an allowed timeframe of [10AM - 8PM](https://github.com/artsy/gravity/blob/b57aae7f42f33243ab64381d14b0f85649f12351/app/services/push_notification_service/scheduler/collector_experience_and_gmv.rb#L10). What this means is that if _in your timezone_ it is 9AM, you will not receive the notification until an hour later, which was the case with this auction. In addition, if in your timezone it is past 8PM, you won’t receive the notification until 10PM the next morning.

This option made sense for non-live auctions that take multiple days, but in the case of a Live Auction I think it makes less sense, as by the time you receive the notification dozens of lots will have already passed.

I suggest we change the Live Auction opening notification to:
- Always send notifications at the real time, regardless of time zone.
- In case, in the user’s local time zone, the time is outside of the allowed timeframe, and the user registered for
  - _this specific_ Live Auction, **do** play a sound.
  - _a different_ auction, **don’t** play a sound.

/cc @sweir27 @devangt @katarinabatina Thoughts?

**Comment by alloy** [comment]
@sweir27 See https://github.com/alloy/time_zone_scheduler for the scheduling options and docs.
