### ISSUE TITLE
[Home] Add placeholders for content to be loaded

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1819]
In the style of Force:

<img width="1280" alt="screen_shot_2016-08-30_at_12 09 06" src="https://cloud.githubusercontent.com/assets/373860/18202433/c6957bae-7107-11e6-8e3b-a5c77a0a8ac3.png">

**Comment by alloy** [comment]
@katarinabatina I was discussing this with @mennenia and we arrived at the conclusion that it’s not as simple as it is in Force, because we show a masonry grid of artworks instead of a simple horizontal rail, so in our case we won’t know how large artworks will be beforehand and the difference between the placeholders layout and the real layout might be very different.

Can you let me know your thoughts on this issue?

I’m punting on this for now.

**Comment by katarinabatina** [comment]
@mennenia @alloy how does loading work right now? Do we prioritize any of the content first? (aka: loading content top to bottom in the feed).

**Comment by alloy** [comment]
We don't right now, we probably could and should soon. How would it relate to this?

**Comment by alloy** [comment]
Oops.

**Comment by alloy** [comment]
@katarinabatina bump

**Comment by katarinabatina** [comment]
Unrelated but I feel like content loads in at different points in the feed and it may be worth while to provide one dummy placeholder at the top of the feed that prevents users from seeing any content until it gets replaced all at once (perhaps then it won't be weird that the content that we actually load in is quite different). I'd say overall though the current expereince isn't a launch blocker.

**Comment by katarinabatina** [comment]
Haven't come to any conclusions about next  best steps here, going to close for now.
