### ISSUE TITLE
Website gene is not loading artworks grid

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1984]
![image_0](https://cloud.githubusercontent.com/assets/2712962/20005052/234314d8-a290-11e6-99dc-5a0dbede4314.jpg)

### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/37020/feedback/648743](https://rink.hockeyapp.net/manage/apps/37020/feedback/648743)

**Comment by katarinabatina** [comment]
follow the gene, go to your home feed, access the gene from home feed by viewing all

**Comment by sarahscott** [comment]
Interesting approach - instead of passing in an array to the `artworks` prop [the way we do in the ArtistVC](https://github.com/artsy/emission/blob/master/lib/components/artist/artworks/index.js#L69), the GeneVC initializes its infinite scroll grid [with an empty array](https://github.com/artsy/emission/blob/master/lib/components/gene/artworks.js#L21).

The question now is why the grid will render works for some genes but leave things blank for others.
