### ISSUE TITLE
remove weird confirmation screen that occurs after connecting with facebook

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1991]
I don't think this screen is necessary at all, I'm not sure why we are showing it. I think the user can just continue into the app after they've authorized facebook. 

![image](https://cloud.githubusercontent.com/assets/6482926/19949815/55ae468e-a12a-11e6-9c63-9c774cb4cac2.png)

**Comment by mennenia** [comment]
Had a chat with Orta about this - it's because we're not guaranteed the email address. 

We're still using an older version of the FB login SDK also. 

I'll have a crack at how much hassle it is to update, and do so if reasonable. Then the idea is to only show this screen if there was no email or something (although you can't have a FB account without email, so if they give us permission, by definition we _should_ have it..)

**Comment by katarinabatina** [comment]
I've been testing FB login with some other apps, seems like it would be valuable to update to their most recent SDK, it definitely "feels" faster/easier than what we're currently using.
