### ISSUE TITLE
Onboarding QA

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#2172]
- [x] can't access results for artists/categories after typing and using (x) or done. We should reload the top lists for artists/categories in this case. https://cl.ly/43150t3w1F1Q https://cl.ly/0C3O301q2V3E

- [x] change ipad helper text, input text and additional below field text all to 26px 
![image](https://cloud.githubusercontent.com/assets/6482926/22935700/55d26c76-f2a1-11e6-8c89-f39af8af0eb7.png)

- [ ] use separate 1px link line vs default underline text for links 
![image](https://cloud.githubusercontent.com/assets/6482926/22935732/68988732-f2a1-11e6-80e7-61d1b7d6a533.png)
![image](https://cloud.githubusercontent.com/assets/6482926/22935754/7cbde914-f2a1-11e6-817e-371007ea7c47.png)

- [x] change all helper text, input text and additional below field text all to 20px 
![image](https://cloud.githubusercontent.com/assets/6482926/22936106/7be4d024-f2a2-11e6-80f6-05250b9fc252.png)

- [ ] there's a sizable delay between submitting my name and moving forward to personalization 
![image](https://cloud.githubusercontent.com/assets/6482926/22945167/388a43ee-f2c1-11e6-9795-cdae4c900530.png)

- [x] replace purple spinner with white one https://cl.ly/1s1E3O3J0Q2w

**Comment by mennenia** [comment]
So I've ticked all the ones I could do - two remain:

**The underline spacing on the buttons:**
I can't control that line, and it's quite difficult to draw a line separately with a pixel distance mid-sentence, if you're not using an underline style. Sorry :(.

**The delay between account creation and personalisation:**
That is probably because we are indeed creating an account, and hence there's a bit of network activity. I think it's best to keep that work in that specific step, because if any errors surface as a result, we need to display them to the user there and then. Whatcha think?

If you'd like me to make any further changes, please re-open!

**Comment by katarinabatina** [comment]
@mennenia underline note is helpful thanks. I actually got some feedback that we should try to make the facebook callout stronger than a text link (still needs to be less than the full button we had during testing) I figure something like this might work but getting it done for Thursday may be difficult https://cl.ly/100S3g41071E 

On the account creation. Should we surface a loading spinner in the [NEXT] button after it is pressed so that the user has some feedback?

**Comment by mennenia** [comment]
Both should be possible - let me do the analytics and tests first, and then I think I can sort this tonight.

**Comment by alloy** [comment]
Closed by #2161
