### ISSUE TITLE
Navigation buttons not showing properly in Fair -> Artist details

### ISSUE THREAD

**Issue by pedrovereza** [artsy/eigen#2195]
In Fair -> Artists -> Artist detail, buttons linking to artwork and "Artist at Artsy" look like this:

<img src="https://cloud.githubusercontent.com/assets/1916041/23305459/9ec87b12-fa7d-11e6-8b62-06f225ddc160.png" width="300">

The `ARNavigationButton`s are directly added to the `stackView`, which is different from all other places that use `ARNavigationButton`. Seems like the common usage is to add the button in a `ARNavigationButtonsViewController` and then add the view to `stackView`. (For example, the ["More Info" button in Artwork](https://github.com/artsy/eigen/blob/master/Artsy/Views/Artwork/ARArtworkActionsView.m#L244)). In fact, the only other place I could find that is using `ARNavigationButton` directly is `ARArtistViewController`, which was replaced by an Emission component. 

As a test, I changed the Artist at Artsy button to use `ARNavigationButtonsViewController`:

```objective-c
- (void)addArtistOnArtsyButton
{
    NSString *title = NSStringWithFormat(@"%@ on Artsy", self.artist.name);

    NSArray *buttonDescription = @[ @{
                               ARNavigationButtonClassKey : ARNavigationButton.class,
                               ARNavigationButtonPropertiesKey : @{
                                       ar_keypath(ARNavigationButton.new, title) : title
                                       },
                               ARNavigationButtonHandlerKey : ^(UIButton *sender) {
                                   UIViewController *viewController = [ARSwitchBoard.sharedInstance loadArtistWithID:self.artist.artistID inFair:nil];
                                   [self.navigationController pushViewController:viewController animated:ARPerformWorkAsynchronously];
                               }
                            }];

    self.artistOnArtsyVC = [[ARNavigationButtonsViewController alloc] init];
    [self.artistOnArtsyVC addButtonDescriptions:buttonDescription unique:YES];
    self.artistOnArtsyVC.view.tag = ARFairArtistOnArtsy;

    [self.view.stackView addSubview:self.artistOnArtsyVC.view withTopMargin:@"20" sideMargin:@"40"];
}
```

which fixed the issue (and the button still works :smile:):

<img src="https://cloud.githubusercontent.com/assets/1916041/23305846/76f9710c-fa7f-11e6-8273-7c0ea2e1d5b7.png" width="300">

For the button that links to an artwork however, I am not sure how to proceed. It would require having an `ARNavigationButtonsViewController` for each artwork, which makes me think that maybe the whole thing should live in its own view controller (button, image and description). This is a bit of extra work, so I'd like to confirm the approach is good before starting on it.

On a side note, I tried a few things to make the buttons to show properly without needing `ARNavigationButtonsViewController`, but no success. Curious to know if I missed an easier solution 🤔

**Comment by orta** [comment]
Ah, now this is a view controller I've not seen in a while! Let me load up the code and have a dig around too.

**Comment by alloy** [comment]
@pedrovereza Awesome and thanks so much 🙌

**Comment by orta** [comment]
Alright, so first off, I always add things like this to my Developer Extras:

```objc

#import "ARFairArtistViewController.h"
#import "Fair.h"

...

- (void)runDeveloperExtras
{
    Fair *fair = [Fair modelWithJSON:@{ @"id": @"the-armory-show-2017"}];
    // many: catpc
    // one: derrick-adams
    ARFairArtistViewController *artist = [[ARFairArtistViewController alloc] initWithArtistID:@"derrick-adams" fair:fair];
    [self pushViewController:artist animated:YES];
}
```

it makes code-injection, and quicker iterations possible when digging into things like this.

---

So yeah, it does feel like a bit of an overkill to build out a whole view controller, for literally a button. It does work, and I have a rough idea of why.

With the migrations  iOS9  we started having to be more specific in our constraint handling around those buttons - we then churned multiple times https://github.com/artsy/eigen/commit/10c834d3d38fa4b03025cb525ce9a11d9b98ccd5#diff-431ad96c54a83bc906d72abc4db4a210L90 https://github.com/artsy/eigen/commit/ef4dd69e8bfe3cb41960ba9050468674955813dc#diff-431ad96c54a83bc906d72abc4db4a210 https://github.com/artsy/eigen/commit/18bac0714af65355bd06ad926bfe562c8ba1a25c on whether, and when to apply the constraints to these buttons.

I think if they live inside their own view controller, they get an an extra "you really do need to render the height of the string before applying the height constraint of the title" - this could maybe be a part of the stack view specific for view controllers too. Not certain.

So, summary, I'd definitely accept a PR converting them to view controllers - at least everything is consistent then, and these are very slow changing view controllers.

I doubt the changes would fail our CI. As the [snapshots look like we expect](https://github.com/artsy/eigen/blob/master/Artsy_Tests/ReferenceImages/ARFairArtistViewControllerSpec/without_maps_looks_correct_show_subtitle_with_a_birthdate_and_a_nationality@2x.png): 

![screen shot 2017-02-24 at 16 50 30](https://cloud.githubusercontent.com/assets/49038/23312360/5e72770a-fab1-11e6-96f3-f031acf7fdba.png)


This is likely because of https://github.com/artsy/eigen/commit/10c834d3d38fa4b03025cb525ce9a11d9b98ccd5#diff-431ad96c54a83bc906d72abc4db4a210L90 making them be rendered to a UIWindow where they are not doing so much async work (if I had to guess )

**Comment by orta** [comment]
lols, I take it back WRT the tests.
https://github.com/artsy/eigen/blob/master/Artsy_Tests/View_Controller_Tests/Fair/ARFairArtistViewControllerTests.m

**Comment by pedrovereza** [comment]
@orta Cool, the developer extra thing really makes life easier, thanks!

I'll go ahead with trying to combine the "artwork to show" details into its own view controller. Aiming to have something before the end of next week.
