### ISSUE TITLE
OSS - submodule path, client key errors

### ISSUE THREAD

**Issue by mparrish91** [artsy/eigen#2248]
I'm trying to get setup with the app as OSS.
I'm running into two erros

1. Direct fetching of that commit failed
"parrys-Air:eigen parry$ git submodule update
error: no such remote ref c68592e3fd42eb38fff0b955cc2ea2191e097caa
Fetched in submodule path 'Pods', but it did not contain c68592e3fd42eb38fff0b95"

When trying to run - make oss
![screen shot 2017-03-28 at 11 11 26 pm](https://cloud.githubusercontent.com/assets/5642923/24440936/f33a605a-140b-11e7-89d7-11a5fbb7bee5.png)

2.  " CocoaPods-Keys has detected a keys mismatch for your setup.
 What is the key for ArtsyAPIClientKey"

when trying to run - bundle exec pod install

**Comment by orta** [comment]
@alloyis it possible you didn't push the pod-artifact commit as a part of https://github.com/artsy/eigen/commit/3ac6c3d0d3001518e2247c4f8f2f6fbece1aaec1 ?

Might make a danger rule for this.

The 2nd issue Is because the first one fails, check out the makefile and run the `bundle exec pod keys [x]` command 👍

**Comment by alloy** [comment]
Yup, my bad! @mparrish91 please try again.

@orta Danger rule sounds like a great idea 👍

**Comment by mparrish91** [comment]
thank you :)
