### ISSUE TITLE
Potential upcoming issue with Sentry

### ISSUE THREAD

**Issue by orta** [artsy/eigen#2347]
It's hard to know till we have it working in prod, but right now Sentry is reporting our Emission URLs like: `app:///Emission.js`

![screen shot 2017-05-17 at 12 10 49](https://cloud.githubusercontent.com/assets/49038/26151283/fe480294-3af9-11e7-8bf8-719f4cc65621.png)

So we may need to [change this](https://github.com/artsy/eigen/blob/master/fastlane/Fastfile#L80) to be the URLs they reference.

**Comment by orta** [comment]
This could back up my idea of "web urls" being why we were having "file 419" collisions in https://github.com/artsy/eigen/pull/2333#issuecomment-301834872

**Comment by alloy** [comment]
> So we may need to change this to be the URLs they reference.

I don’t follow. I think it just uses the filename of the bundle because there’s no sourcemaps.

Can we upload sourcemaps for this staging release with `sentry-cli` perhaps and see if it symbolicates properly afterwards? Or is that not possible for the same reason we disabled `eigen-staging` uploads during the fastlane build?

**Comment by orta** [comment]
I think we could, would need to re-trigger the bug though - don't think it re-symbolicates old crashes

**Comment by alloy** [comment]
I think Hockey would re-symbolicate when new symbols got uploaded, which kinda makes sense to me
