### ISSUE TITLE
Remove map button from Artists at the Fair View

### ISSUE THREAD

**Issue by orta** [artsy/eigen#24]
_From @katarinabatina on January 13, 2015 20:28_

Current build has the map preview and the button, should remove the button 
current
![image](https://cloud.githubusercontent.com/assets/6482926/5728495/a96196e0-9b38-11e4-9ee8-da5133ab7daf.png)

change to 
![image](https://cloud.githubusercontent.com/assets/6482926/5728516/d777fb1e-9b38-11e4-85bf-8d28c7611c0a.png)

_Copied from original issue: artsy/eigen-private#2116_

**Comment by alloy** [comment]
@katarinabatina 

This is the **before** state:

![ios simulator screen shot 02 feb 2015 14 00 25](https://cloud.githubusercontent.com/assets/2320/6000925/49293fd8-aae4-11e4-83ac-9d978e31d341.png)

And this is the current **after** state:

![ios simulator screen shot 02 feb 2015 13 57 37](https://cloud.githubusercontent.com/assets/2320/6000931/529a3306-aae4-11e4-9c87-0bfd3e3ce9ae.png)

----

Some things I noticed in your design, but weren’t 100% clear because we couldn’t find ‘Waldemar Cordeiro’ amongst the artists, and would like to have clarified if these need to be changed as well:

* The `[City] Born [Year]` subtitle:
  - moved underneath the title
  - has been center aligned
  - changed to grey

* The pins on your map are grey, whereas they seem to all be purple in the current app.

**Comment by katarinabatina** [comment]
Hi Alloy! Welcome, welcome!

The three bulleted changes you mentioned should be changed to the design you saw, move the and center the title, and change to the dark grey.

Currently non selected pins should show grey while selected should show purple. In the case of this map preview the highlighted pin should be purple, if there are two pins, both should be purple.

**Comment by alloy** [comment]
Hi hi @katarinabatina, thanks for the warm welcome!

I’m not yet completely clear as to how literally I should take the mock-ups, but that’s something to discuss during the Eigen stand-up, I suppose.

In any case, here’s the current iteration:

![ios simulator screen shot 03 feb 2015 16 02 13](https://cloud.githubusercontent.com/assets/2320/6022698/02c1cf20-abbf-11e4-9cb2-918ea05305e6.png)
