### ISSUE TITLE
the armory booth for Sies + Hoke gallery shows up on artsy.net and on m.artsy.net but NOT on the iPhone app

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#255]
![screen shot 2015-03-04 at 11 19 36 am](https://cloud.githubusercontent.com/assets/542335/6487642/6a32a316-c260-11e4-821c-620401039e04.png)

![2015-03-04 11 20 17](https://cloud.githubusercontent.com/assets/542335/6487790/4701e4dc-c261-11e4-80b7-3471cd1702ba.png)

**Comment by dblock** [comment]
@dylanfareed and I have a $1 bet that this is a problem with the special character in the gallery name, please keep us posted :)

**Comment by dylanfareed** [comment]
Hits I think this endpoint 

![image](https://cloud.githubusercontent.com/assets/197336/6487834/6e5a5d48-c261-11e4-87d4-134ef7b151ac.png)

**Comment by alloy** [comment]
Interesting, I reproduce the same when searching from the Armory overview screen. I _can_ find the booth from e.g. the search on the map screen.

I’ll dive deeper into this once I’m back from doing grocery shopping.

**Comment by alloy** [comment]
Ok, so the issue is that the `ARFairSearchViewController` [rejects any search result that is _not_ locally stored data](https://github.com/artsy/eigen/blob/2e814fc6216f88c61a2373a2e35db369695e6dba/Artsy/Classes/View%20Controllers/ARFairSearchViewController.m#L97-L100). Because loading the map stores all the data locally, navigating to the map at least _one_ will make it show up in the search results.

This behaviour was introduced by [this change](https://github.com/artsy/eigen-private/pull/1198). I wasn’t able to reproduce an issue of ‘duplicate’ search results showing up, but I’m afraid that it might be more of an issue of me not fully understanding the original problem, as the screenshot there also doesn’t show me ‘kohn’ twice.

----

Having said all that, after reverting that change, I get the following successful result (on a cold cache) and am able to navigate to the detail page for that partner:

![ios simulator screen shot 04 mar 2015 19 06 22](https://cloud.githubusercontent.com/assets/2320/6489970/0b35cf58-c2a3-11e4-93b4-d74566107781.png)

Note, however, that the title is different from the local data _after_ loading the cache:

![ios simulator screen shot 04 mar 2015 19 07 01](https://cloud.githubusercontent.com/assets/2320/6489984/1a55d1d6-c2a3-11e4-999f-4689211b5229.png)

**Comment by alloy** [comment]
I am going to (try to) perform my first App Store release tomorrow morning. Do you want me to include the reversal of this change?

I’m slightly hesitant because I can’t reproduce the original issue that it fixed.

/cc @orta @1aurabrown

**Comment by alloy** [comment]
For completeness sake, here’s a clip showing the current issue and how loading the cache (by visiting the map) makes it show up:

![booth searchable once map has loaded](https://cloud.githubusercontent.com/assets/2320/6490084/fb73e4d2-c2a3-11e4-9260-d96e33541c65.gif)

**Comment by dylanfareed** [comment]
Can for the purposes of the bet I have with @dblock we just say its because of the character in the name?

**Comment by dblock** [comment]
@alloy I think that change was introduced because search used to do a combination of local search from cache (shows) and active live search from the internet. This way you could find shows locally even if you don't have a good connection, it was also a lot faster to show things. I am not sure how this code changed, but ultimately I think that's what we want. How did search on the map evolve?
