### ISSUE TITLE
Implementation Question: Requests as Class Methods

### ISSUE THREAD

**Issue by andrewjburnett** [artsy/eigen#324]
I'm in the early stages of developing an iOS application, which will consume a REST API. While GitHub, Apple docs, tutorials, etc. have been helpful in answering the majority of my questions thus far, I've recently experienced some hiccups while trying to learn more about networking. I haven't found an good, consolidated source of information regarding best practices/design patterns related to building out the networking layer of an application. I recently came across the source code for Artsy and have been reading over it as a guide to building a framework for consuming an API.

I do have a few questions though. Please, forgive me if they sound naive. Why is that the majority of the actual requests are implemented as class methods? What are the advantages of this approach, as opposed to creating some sort of "shared" singleton, which you would use to instantiate/get an instance of ARRouter and then make requests?

Also, there are calls to these ArstyApi class methods spread throughout. However, I don't understand exactly where/how this class is declared globally, allowing it to be recognized across many different class implementations.

Lastly, do you have plans to "Reactify" any portion of the networking layer. From what I've gathered, ReactiveCocoa and the functional programming it enables is a great fit for code that is heavy with callbacks/handlers, etc. A few other articles and iOS source code examples I have come across (SoundCloud and Timehop) have mentioned that if they haven't already done so, they were at least planning to adopt a more "Reactive" style within upcoming iterations of their code, specifically the networking layer.

Thanks for the help!

**Comment by orta** [comment]
How we came to what we have:

Networking right now happens in three places in

**Comment by andrewjburnett** [comment]
Accidentally closed this issue. Reopening it now.

**Comment by orta** [comment]
> Why is that the majority of the actual requests are implemented as class methods?

This is personal, but I've always favoured the look of class methods over `[[bleh sharedBlah] method:x y:z]` especially for things that feel atomic and stateless. This has changed a little bit over time as I've moved to writing `[bleh.sharedBlah method:x y:z]` but in general I've not really seen a really strong desire to move in that direction.

> Also, there are calls to these ArstyApi class methods spread throughout

Networking is done in 4 ways at the minute, 

  * Network Models
  * Promises
  * Model networking
  * Raw API access

They all have different use cases, and came about from different constraints. The network models make it really easy to test code, promise based networking makes it easy to hook a lot of callbacks into the same request, model networking can make it feel like it's just an asychronous call to fetch some data. And accessing the raw api methods is for when we've had time constraints. 

There's discussion on our [Mobile repo](https://github.com/artsy/mobile/issues/22) around trying to unify into a single pattern. More on that in your next question.

> Lastly, do you have plans to "Reactify" any portion of the networking layer

We've done this once, and it worked out really well. This is the networking stack for [Eidolon](https://github.com/artsy/eidolon) called [Moya](http://cocoapods.org/pods/Moya), and it looks [like this](https://github.com/artsy/eidolon/blob/master/Kiosk/Bid%20Fulfillment/ConfirmYourBidViewController.swift#L61-L62):

```
  let endpoint: ArtsyAPI = ArtsyAPI.FindBidderRegistration(auctionID: nav.auctionID!, phone: String(self!.number))
  return XAppRequest(endpoint, provider:self!.provider, parameters:endpoint.defaultParameters).filterStatusCode(400).doError { (error) -> Void in

  /// error
  
  } . then {
    /// return next signal
    
  }
```

I'm not entirely sure on how well Moya's enum style can scale for something like eigen, given that for the  ~30 routes eidolon uses, it's a 360+ lines of code long API client, even roughly guessing I'd expect eigen to have a hundred plus routes. With a lot more custom messing around. Plus it's swift only, and that's not really [production ready](http://ashfurrow.com/blog/production-swift/) for us.

I've explored methods of generating [NSURLRequests automatically](https://github.com/orta/GotTheRoutesLikeSwagger) using documentation so that we can try and concentrate on something that fits similar constraints to what we have for Moya:

* Can easily run asynchronously or synchronously in tests, and stubs as first class citizens
* Allow iterating through all potential API requests at runtime for API sanity checks.
* Enforce using of the API, and not allowing people to take shortcuts
* A structure that makes it easy to allow multiple listeners to the same request

I've spent time with ReactiveCocoa now, but I'm not sure I'd want to build more things on it personally. The eigen codebase allows you to work with RAC if you choose, but you can also carry on fine wihtout. I wouldn't want our networking to be purely rac based. I think we could re-thing the promise-based networking into a useful system, which is what we were doing a lot in Eidolon.

**Comment by andrewjburnett** [comment]
Thank you very much! Going to read this over and soak it in.

**Comment by orta** [comment]
Closing for now, would recommend keeping an eye on https://github.com/artsy/mobile/issues/22 for upcoming ideas around this
