### ISSUE TITLE
Facebook / Twitter link hijacking doesn't work on ipad

### ISSUE THREAD

**Issue by orta** [artsy/eigen#367]

**Comment by alloy** [comment]
I’m gonna see if we can get the martsy views to not include the twitter/facebook badges in Eigen so that it works more like a native view.

**Comment by alloy** [comment]
**[ESTIMATE]** 2 days

**Comment by ashfurrow** [comment]
Gonna take this, sans native buttons.

**Comment by ashfurrow** [comment]
This is occurring because – on the iPad, apparently – `webView:shouldStartLoadWithRequest: navigationType:` sends a navigation type of `UIWebViewNavigationTypeOther`, which [we exclude](https://github.com/artsy/eigen/blob/7082c041a314a7ab7541c154ec633918539c9813/Artsy/Classes/View%20Controllers/ARInternalMobileWebViewController.m#L111). 

My proposed solution is just to add `.Other` to the `if` statement.

**Comment by ashfurrow** [comment]
... which actually really doesn't work. Hmm.
