### ISSUE TITLE
[QUESTION] Checking Pods into source control

### ISSUE THREAD

**Issue by tabuchid** [artsy/eigen#418]
The cocoapods guide suggests checking your Pods into source control https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
You don't do that here. What went into that decision?

**Comment by orta** [comment]
Checking in Pods makes sense if you:

 * Are writing projects that get left alone for long periods of time
 * Are writing projects where some people don't use CocoaPods 
 * Want to be able to just clone and run
 * Don't trust that the source code for other projects will be around
 * Don't use CocoaPods-Keys ( checking in `Pods/` in this case checks in your API keys )

We have an expectation that developers should know how to deal with dependencies, both in ruby and in Cocoa. As CocoaPods, we want to tell people that they don't have to learn all this. As Artsy, I think we do.

Finally, I don't want to see bloated PRs as the Pods dir changes. I personally think vendored code should stay out of source control for a project. 

ps. I would like to one day make a `pod archive` command that zips up a release + source and backs it up to S3 for storage someday per-beta / release. I think that's a better use of space, and allows us to look back and run older builds if needed. Two years in to eigen, though, we've not needed to ever re-build a specific build that couldn't be done via `bundle install` & `bundle exec pod install`.

**Comment by tabuchid** [comment]
:+1: Thanks @orta

**Comment by alloy** [comment]
I agree with @orta that on a project we work daily on and only with devs that have no problem with setting up these dev environments it’s less of an issue to not check the Pods directory in.

On some of our lower traffic libraries (e.g. [Artsy-UIButtons](https://github.com/artsy/Artsy-UIButtons)), however, I would personally prefer to check them in for ease. E.g. in that case you have to change into the example dir and run `pod install`, something you tend to forget and then you let Xcode run only to afterwards find out it didn’t run because you didn’t run `pod install` yet.

I guess I’m just pragmatic > being principal and prefer to perform less steps to building ¯\_(ツ)_/¯
