### ISSUE TITLE
"you" section no longer triggers sign up CTA 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#463]

**Comment by orta** [comment]
Estimate: 2-3 hours

**Comment by 1aurabrown** [comment]
i'm also not seeing this in the beta (on iPhone). will try on iPad simulator as I don't have a physical iPad with me

**Comment by 1aurabrown** [comment]
yeah, not able to repro in iPad sim either ¯\\\_(ツ)_/¯

**Comment by orta** [comment]
This happened to me when I last tested, try a full wipe & re-install?

**Comment by orta** [comment]
This worked for me when I tested it just now.

**Comment by ashfurrow** [comment]
Could this be caused by an expired XApp token? We rely on having a valid token when determining if a user is a trial user or not: https://github.com/artsy/eigen/blob/b49c2b9021fedb07dfa67eaf9e10e0e656fb3d76/Artsy/Classes/Models/User.m#L10-L14

The [original commit by Orta](https://github.com/artsy/eigen-private/commit/5d3b32f2664795cc045cade9b5f17bf5db268d89#diff-134f9050f8fc18d2ed12b51f7aa03a43R25) doesn't specify why we need a valid XApp token to be considered a trial user. 

Maybe we should just infer "no currently logged in user" implies "you are a trial user"? @orta?

**Comment by ashfurrow** [comment]
Yeah, I think this is it. I'm betting this is why we're checking for a trial user in this way:

The user is `nil`, but the XApp token isn't valid. This means we _might_ be waiting on an XApp token to get back from the network, and when we do, we'll have a valid token (and possibly a user to go with it). 

In general, eigen is pretty bad at refreshing XApp tokens (only some requests make sure we have one first). I'm going to change this code to check if a user is logged in, and ignore the XApp token. The possible downside is that a user who has logged in some other time, but is now accessing Artsy on an _incredibly_ slow network, _may_ be asked to sign in again if they tap "You". This would affect favouriting things in the same way, too.
