### ISSUE TITLE
works for sale data on artist page is correct but loads oddly

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#469]
come to artist page, selected all works tab does not reflect all works available, switch to works for sale tab, then all works appear, switch back then all works still appear, switch to works for sale then accurate amount is surfaced 

http://cl.ly/image/2x300G3y1J06

another example where this is more clear http://cl.ly/image/2v2m292b3e3Y

![https://s3.amazonaws.com/f.cl.ly/items/0W250C423h3T3e113S2V/Screen%20Recording%202015-05-21%20at%2011.25%20AM.gif](https://s3.amazonaws.com/f.cl.ly/items/0W250C423h3T3e113S2V/Screen%20Recording%202015-05-21%20at%2011.25%20AM.gif)

**Comment by orta** [comment]
Could be that somewhere we're reseting our  collection view layout on an append?
Estimate: 1/2 day

**Comment by ashfurrow** [comment]
Alloy and Laura both have confirmed that the API is returning accurate results.

**Comment by ashfurrow** [comment]
Well, looks like it's always showing only ten artworks, which is the page size. Wondering if the fetch for the next page just isn't being triggered.

**Comment by ashfurrow** [comment]
What if this is just only fetching the first then, then waiting for the user to scroll to load more? Except since the collection view isn't showing enough content already to scroll at all, more aren't loaded? 

On the iPhone, ten artworks would certainly overflow the width of the screen, so you could always scroll to get more. But on the iPad, only loading ten means you can't load subsequent pages.

**Comment by ashfurrow** [comment]
Additional artworks are only loaded in one of three cases:

![screen shot 2015-06-02 at 1 35 38 pm](https://cloud.githubusercontent.com/assets/498212/7942454/4ae18744-092c-11e5-8111-62df1a7cf51b.png)

- When the artist is first displayed (which is where our bug is presenting).
- When the user scrolls enough to trigger the next page to load (which they can't do, since collection views don't scroll unless they have enough content to).
- When the display mode (All/For Sale) is changed (which is why more are loaded when you switch from All to For Sale and back to All).

**Comment by ashfurrow** [comment]
I think the best possible solution would be to check if we haven't overflowed the collection width and if there are more artworks we can download.

**Comment by alloy** [comment]
@ashfurrow That sounds like a good fix :+1: and would look much nicer anyways, there’s no reason to not fill the width of the iPad screen when there is more work available.

**Comment by ashfurrow** [comment]
OK, will implement :)

**Comment by katarinabatina** [comment]
:+1:

**Comment by ashfurrow** [comment]
It also worries me that – as the code exists right now – duplicate artworks are introduced into the collection view. This exists in the beta as well as the app store release.

**Comment by ashfurrow** [comment]
Looks like it duplicates the first ten artworks. 

![screen shot 2015-06-02 at 2 30 42 pm](https://cloud.githubusercontent.com/assets/498212/7943693/20136be2-0934-11e5-99e7-979a146e4368.png)

**Comment by alloy** [comment]
@ashfurrow Excellent find!
