### ISSUE TITLE
After signing-in ‘works for you’ is missing from home screen

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#513]
1. Don’t sign-in during startup
2. Let ‘HOME’ screen load
3. Tap ‘YOU’ and sign-in
4. Go back to ‘HOME’ screen
5. Observe that there is no ‘Works for you’ section.

Presumably, this is because the home screen would need to be reloaded.

**Comment by katarinabatina** [comment]
are you talking ipad or iphone?

**Comment by alloy** [comment]
This was iPhone.

**Comment by katarinabatina** [comment]
if we're implementing the bell this sprint this issue is probably not going to be a problem correct?

**Comment by alloy** [comment]
@katarinabatina Not sure how that’s related, can you elaborate on that?

**Comment by alloy** [comment]
Moving this to #489.

**Comment by katarinabatina** [comment]
@alloy the problem is here that the "works for you" link that is created in admin is not surfacing, some type of communication failure. But as we move to the bell in the home navigation and embedding the microgravity view behind that tab we will no longer be using that "featured link" that we currently do. Seems like it would be wasted time to figure out what the problem is with that link since we will no longer be using them at all in Eigen.

**Comment by alloy** [comment]
@katarinabatina Gotcha. I’m not gonna look at that specifically anymore anyways, #489 is about the issue in general, namely that the home view should be reload after a user signs-in in general.
