### ISSUE TITLE
Scroll to top..

### ISSUE THREAD

**Issue by dkhamsing** [artsy/eigen#523]
Congrats on v2, the app looks great

The bug: scroll to top stops working
1. When the app first starts (home), scroll down and tap the status bar: scroll to top :tada: 
2. Tap another tab (shows or explore), scroll down and tap the status bar.. :cry:

**Comment by alloy** [comment]
> Congrats on v2, the app looks great

Thanks! @1aurabrown Did a great job indeed.

> The bug: scroll to top stops working

Sorry to hear we broke something, but what a great and concise bug report. Thanks! :heart:

**Comment by alloy** [comment]
What’s more, scroll to top is also broken on the home screen once you go back from any of the other tabs.

**Comment by ashfurrow** [comment]
The docs say that after tapping on the status bar, iOS will check the scroll view closest to the menu bar if it should scroll to top. It also says if more than one scroll view says `YES`, then nothing happens.

My theory is that when switching tabs, we add another view controller to the root VC's hierarchy. But we never remove old view controllers from this hierarchy, which must be used by iOS to determine which scroll view is closest to the status bar. 

@alloy I've confirmed this on the simulator, but am again fighting with profiles on my home computer. I'll verify on device, then send a PR.

**Comment by alloy** [comment]
@ashfurrow I’d prefer you spend working on code the last few hours you’re still here, so just remind me to test it on device. I want to put out a beta anyways.

**Comment by ashfurrow** [comment]
:+1:

**Comment by 1aurabrown** [comment]
All kinds of rotation problems happen if we remove VCs from the top vc, because
then they don't get size change notifications when rotating and not visible. Is
there some way to avoid doing that?


On Fri, Jul 3, 2015 at 17:15, artsy/eigen
<reply@reply.github.com>
wrote:
:+1: [https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/eigen/issues/523#issuecomment-118426798] .[https://github.com/notifications/beacon/ADBlTvS05Wu9BtH8RL7euM2axGF6Uw85ks5oZvLtgaJpZM4FGtBv.gif]

**Comment by ashfurrow** [comment]
Hmm. Not that I am aware of. It sounds like this could turn into a bigger issue. I'll check and see if other tab bar implementations have something to deal with that.

**Comment by ashfurrow** [comment]
Nah, can't seem to find anything like an easy fix. This is going to be more than a simple fix – gonna get those other small ones.

**Comment by ashfurrow** [comment]
Shoot, thought this was the PR :)

**Comment by 1aurabrown** [comment]
I'm super opposed to removing stuff from the view hierarchy because it creates a
nightmare on ipad. Can we toggle something when the scroll view
appears/disappears to ensure thay only one scroll view in the hierarchy is
returning YES, and that it is the one that's actually visible?

On Fri, Jul 3, 2015 at 18:06, artsy/eigen
<reply@reply.github.com>
wrote:
Shoot, thought this was the PR :)

—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/eigen/issues/523#issuecomment-118432737] .[https://github.com/notifications/beacon/ADBlTljT8AgElI2lzKBE2aNNo7m_O8owks5oZv7jgaJpZM4FGtBv.gif]

**Comment by ashfurrow** [comment]
Yes, that would work. What I'm confused by is that we seem to be the only one to have this problem:

1. Show a view controller
1. Show a different view controller
1. Rotate
1. Show the same view controller as before

This seems like it would be a really common problem in the iOS world – I'm curious if someone

**Comment by alloy** [comment]
The fact that we need to keep these hierarchies alive _probably_ point to a larger problem.

**Comment by 1aurabrown** [comment]
It's well documented that a vc will not have size change methods invoked if it
isn't part of the hierarchy
I'm not sure how other people deal with this


On Fri, Jul 3, 2015 at 18:26, Eloy Durán <notifications@github.com> wrote:
The fact that we need to keep these hierarchies alive probably point to a larger problem.

—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/eigen/issues/523#issuecomment-118434644] .[https://github.com/notifications/beacon/ADBlToNqEUTdoEiOL9REgeXbEU49EBlNks5oZwObgaJpZM4FGtBv.gif]

**Comment by alloy** [comment]
@ashfurrow In any case, I think shelling it for now is the good call.

**Comment by ashfurrow** [comment]
Totally.

**Comment by alloy** [comment]
Btw, this is only an issue on the iPhone version, on iPad it works as expected.

**Comment by katarinabatina** [comment]
@alloy is this the best issue to capture the scroll to top issues we've been having or should we close in favor of another ticket?
