### ISSUE TITLE
app permanently stuck without ability to get back online

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#624]
I have been refreshing the app trying to get passed the network error screen for over half the day with no luck. had to delete and restart the app. Previous issues I logged may all be related. Trouble is, I don't know how to reproduce. I think it all started from trying to access the app when there was no network connection and never getting connected again.

**Comment by alloy** [comment]
Yeah this is definitely an issue, also #576. I’m going to look into this now.

**Comment by alloy** [comment]
Is the view in #576 the view you were seeing or is it something else?

**Comment by alloy** [comment]
Ok, I’m now thinking that you might have meant this screen:

![ios simulator screen shot 13 jul 2015 13 33 07](https://cloud.githubusercontent.com/assets/2320/8648778/e34b3f28-2963-11e5-992a-81ceed5d50d8.png)

**Comment by alloy** [comment]
I think that the expectation of [these](https://github.com/artsy/eigen/blob/356b88d1ff035a9f0aa28f19e42255c7152a88f4/Artsy/View_Controllers/Feed_VCs/ARShowFeedViewController.m#L143-L145) [two](https://github.com/artsy/eigen/blob/356b88d1ff035a9f0aa28f19e42255c7152a88f4/Artsy/View_Controllers/Feed_VCs/ARFeedViewController.m#L125-L127) pieces of code is (and maybe it worked like that at some point) that there would be errors yielded if the connection was offline, but that does not appear to be the case, which is why it never tries to load the content again.
