### ISSUE TITLE
Hero unit doesn’t load images if app was launched with connection error.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#669]

**Comment by ashfurrow** [comment]
What does "launched with connection error" mean? That the original request resulted in an error, or that the user had no internet connection?

**Comment by alloy** [comment]
The latter. So:

1. Disable your wifi
2. Launch app
3. Enable wifi
4. App dismisses the ‘no connection’ screen or you do so yourself with the refresh button
5. No hero units on home screen

**Comment by ashfurrow** [comment]
I see. Looks like it's related to keeping the view controllers in the hierarchy, even when they're not visible. This is an issue we've discussed before – since we keep them in the hierarchy, unlike a `UITabViewController`, their `viewWillAppear:` etc methods aren't called directly. 

I know that removing them/readding them complicates the orientation changes on iPad, but I still can't help but feel like there's a better solution that we're not seeing.
