### ISSUE TITLE
Issue in setup process.

### ISSUE THREAD

**Issue by raducanb** [artsy/eigen#734]
There's an issue when I try to setup the app. Maybe it's because I don't have all the prerequisites?

![screenshot 2015-08-19 09 46 23](https://cloud.githubusercontent.com/assets/4189954/9355975/4de986a2-4686-11e5-9667-7b761dd9e5c5.png)

**Comment by orta** [comment]
Hrm, so this looks like you might not have permission to save files to bundler's cache directory. I guess this is because at some point you did a `sudo bundle install`. I would think that `chown  ~/.bundler/` would give you permission to save files to that directory. I got this info [from here](http://stackoverflow.com/questions/13195814/trying-to-git-pull-with-error-cannot-open-git-fetch-head-permission-denied)

@alloy - feels reasonable?

**Comment by alloy** [comment]
Agreed :+1:

**Comment by raducanb** [comment]
I tried and it didn't work :\

**Comment by alloy** [comment]
@raducanb try `sudo chown -R $USER ~/.bundler`

**Comment by raducanb** [comment]
@alloy Same result. I tried deleting that cache folder (see in screenshot), ran the command, but same error. As orta said, I did try running the ```sudo bundle install``` command at some moment, so maybe that broke something. Do you have any other ideas? I didn't find anything else on google.

**Comment by alloy** [comment]
Maybe the problem is with the `/Library/Ruby/Gems/2.0.0/bundler/gems/cocoapods-119c8c765941` dir that it mentions as well. Try removing that also.

**Comment by raducanb** [comment]
You were right. Although I removed the folder shown in the first screenshot, after that the error was the same but the folder changed. In the end I deleted all three folders from "/Users/raducanbogdan/.bundler/cache/git/" and "/Library/Ruby/Gems/2.0.0/bundler/gems/". Thanks for the help.

**Comment by alloy** [comment]
Glad you got this sorted :+1:
