### ISSUE TITLE
Failing Inquiries

### ISSUE THREAD

**Issue by orta** [artsy/eigen#806]
So, we have a higher than expected number of failing inquiries. A look through seems to indicate two things, sorry non-OSS peeps.
- [It's for trail users](https://mixpanel.com/report/275154/segmentation/#action:segment,arb_event:'Inquiry%20error',bool_op:and,chart_analysis_type:linear,chart_type:line,from_date:-167,ms_checked:%28false:!t,true:!t%29,ms_values:!%28false,true%29,segfilter:!%28%28property:%28name:is_trial_user,source:properties,type:boolean%29,selected_property_type:boolean,type:boolean%29%29,segment_type:boolean,to_date:0,type:general,unit:week)
- [It's mostly a 404](https://mixpanel.com/report/275154/segmentation/#action:segment,arb_event:'Inquiry%20error',bool_op:and,chart_analysis_type:rolling,chart_type:line,from_date:-167,ms_checked:%28'A%20server%20with%20the%20specified%20hostname%20could%20not%20be%20found.':!t,'Expected%20status%20code%20in%20%28200-299%29,%20got%20400':!t,'Expected%20status%20code%20in%20%28200-299%29,%20got%20404':!t,'Request%20failed:%20not%20found%20%28404%29':!t,'The%20network%20connection%20was%20lost.':!t,'The%20request%20timed%20out.':!t%29,ms_values:!%28'Expected%20status%20code%20in%20%28200-299%29,%20got%20404','Expected%20status%20code%20in%20%28200-299%29,%20got%20400','Request%20failed:%20not%20found%20%28404%29','The%20request%20timed%20out.','The%20network%20connection%20was%20lost.','A%20server%20with%20the%20specified%20hostname%20could%20not%20be%20found.'%29,segfilter:!%28%28property:%28name:errors,source:properties,type:string%29,selected_property_type:string,type:string%29%29,segment_type:string,to_date:0,type:general,unit:week)

Perhaps somewhere we are generating an incorrect URL for the POST?  Why some and not others?

We should also amend the analytics call for "Inquiry error" to include the URL too - it should exist as `NSURLErrorFailingURLErrorKey`.

**Comment by orta** [comment]
I looked a bit on gravity, and the only potential for getting a 404 is when we couldn't find or create an user [to associate](https://github.com/artsy/gravity/blob/10762caab80f11ff84fa3ec0e05d87a144e494ad/app/api/v1/me_inquiry_requests_endpoint.rb#L59-L60)

**Comment by jorystiefel** [comment]
Looking at [this graph](https://mixpanel.com/report/275154/segmentation/#action:segment,arb_event:'Inquiry%20error',bool_op:and,chart_analysis_type:linear,chart_type:line,from_date:-167,ms_checked:(false:!t,true:!t),ms_values:!(false,true),segfilter:!((property:(name:is_trial_user,source:properties,type:boolean),selected_property_type:boolean,type:boolean)),segment_type:boolean,to_date:0,type:general,unit:week) I believe the error is happening only for authenticated users (when `is_trial_user` is `false`)

**Comment by jorystiefel** [comment]
There are two types of "404" results indicated, one starting around June 25, and the other Sept 10. (see [this graph](https://mixpanel.com/report/275154/segmentation/#action:segment,arb_event:'Inquiry%20error',bool_op:and,chart_analysis_type:rolling,chart_type:line,from_date:-167,ms_checked:('A%20server%20with%20the%20specified%20hostname%20could%20not%20be%20found.':!f,'Expected%20status%20code%20in%20(200-299),%20got%20400':!f,'Expected%20status%20code%20in%20(200-299),%20got%20404':!t,'Request%20failed:%20not%20found%20(404)':!t,'The%20network%20connection%20was%20lost.':!f,'The%20request%20timed%20out.':!f),ms_values:!('Expected%20status%20code%20in%20(200-299),%20got%20404','Expected%20status%20code%20in%20(200-299),%20got%20400','Request%20failed:%20not%20found%20(404)','The%20request%20timed%20out.','The%20network%20connection%20was%20lost.','A%20server%20with%20the%20specified%20hostname%20could%20not%20be%20found.'),segfilter:!((property:(name:errors,source:properties,type:string),selected_property_type:string,type:string)),segment_type:string,to_date:0,type:general,unit:day)). As far as I can tell, these dates don't coincide with any releases on the iOS end.

**Comment by alloy** [comment]
From @jorystiefel in Slack:

> I’m told there were significant changes on the Gravity side to that artwork inquiries around the time we started seeing those 404s, … just an update.

Comparing your last [graph](https://mixpanel.com/report/275154/segmentation/#action:segment,arb_event:'Inquiry%20error',bool_op:and,chart_analysis_type:rolling,chart_type:line,from_date:-167,ms_checked:('A%20server%20with%20the%20specified%20hostname%20could%20not%20be%20found.':!f,'Expected%20status%20code%20in%20(200-299),%20got%20400':!f,'Expected%20status%20code%20in%20(200-299),%20got%20404':!t,'Request%20failed:%20not%20found%20(404)':!t,'The%20network%20connection%20was%20lost.':!f,'The%20request%20timed%20out.':!f),ms_values:!('Expected%20status%20code%20in%20(200-299),%20got%20404','Expected%20status%20code%20in%20(200-299),%20got%20400','Request%20failed:%20not%20found%20(404)','The%20request%20timed%20out.','The%20network%20connection%20was%20lost.','A%20server%20with%20the%20specified%20hostname%20could%20not%20be%20found.'),segfilter:!((property:(name:errors,source:properties,type:string),selected_property_type:string,type:string)),segment_type:string,to_date:0,type:general,unit:day) against the [commit history of Gravity](https://github.com/artsy/gravity/commits/10762caab80f11ff84fa3ec0e05d87a144e494ad/app/api/v1/me_inquiry_requests_endpoint.rb) for that endpoint, it seems to have started around/after [this commit](https://github.com/artsy/gravity/commit/e23f1584503c2d5444ea9355da60fd1bb1ce151c). Since then @sweir27 and @joeyAghion have been doing work on it.

So I guess the question is, are we sending incorrect data in certain cases and, if so, what is that incorrect/missing data?

**Comment by jorystiefel** [comment]
I think we can ignore the June date, as it appears that is when we started tracking these events, so we can just focus on the Sept 10th as the date new 404s started appearing.

**Comment by jorystiefel** [comment]
As it turns out, our baseline rate of 404s has not changed. What has changed is that we switched to AFNetworking 2.0, which rewords the way 404s are explained from:

```Expected status code in (200-299), got 404```
to:
```Request failed: not found (404)```

This caused a new line to sprout up in the Mixpanel graph, but it is not a _new_ problem, per se.

You can see the [AFNetworking change here](https://github.com/AFNetworking/AFNetworking/commit/9a40c0dc0f27e9a547fb173a0b1b5a06072e91f9)

**Comment by jorystiefel** [comment]
Again, referencing (this graph), as the new line of 404s emerges, the existing one declines.

**Comment by alloy** [comment]
Errors will now get submitted to the analytics provider, so hopefully we’ll be able to better diagnose this for the next sprint: https://github.com/artsy/eigen/pull/836

**Comment by orta** [comment]
We're post 2.3.0 - this is Mixpanel for all [Inquiry Errors](https://mixpanel.com/report/275154/segmentation/#action:segment,arb_event:'Inquiry%20error',bool_op:and,chart_analysis_type:rolling,chart_type:line,from_date:-167,ms_checked:('The%20Internet%20connection%20appears%20to%20be%20offline.':!t,'The%20request%20timed%20out.':!t),ms_values:!('The%20request%20timed%20out.','The%20Internet%20connection%20appears%20to%20be%20offline.'),segfilter:!((filter:(operand:!('2.3.0'),operator:%3D%3D),property:(name:'$app_version',source:properties,type:string),selected_property_type:string,type:string),(property:(name:errors,source:properties,type:string),selected_property_type:string,type:string)),segment_type:string,to_date:0,type:general,unit:day) on 2.3.0

Alas we only have one to work with, and that error is that the person submitting the form was offline. We don't have enough information yet.

**Comment by alloy** [comment]
@katarinabatina This is that issue I mentioned at the stand-up.

**Comment by katarinabatina** [comment]
thanks @alloy

**Comment by orta** [comment]
Current known error messages received from gravity:

![screen shot 2015-12-08 at 5 37 48 pm](https://cloud.githubusercontent.com/assets/49038/11670873/6fa10150-9dd2-11e5-9a72-fd34884bd997.png)

**Comment by orta** [comment]
the blank one is the most often, it represents when we do not receive [any data](https://github.com/artsy/eigen/blob/master/Artsy/App/ARAppDelegate+Analytics.m#L425) from Artsy.

A better link to analytics: (here)[https://mixpanel.com/report/275154/segmentation/#action:segment,arb_event:'Inquiry%20error',bool_op:and,chart_analysis_type:rolling,chart_type:line,from_date:-167,ms_checked:('%20/%20Request%20failed:%20not%20found%20(404)':!t,'%20/%20The%20Internet%20connection%20appears%20to%20be%20offline.':!t,'%20/%20The%20data%20couldn’t%20be%20read%20because%20it%20isn’t%20in%20the%20correct%20format.':!t,'%20/%20The%20network%20connection%20was%20lost.':!t,'%20/%20The%20request%20timed%20out.':!t,'Inquirer%20cannot%20be%20an%20admin.%20/%20Request%20failed:%20bad%20request%20(400)':!t,'Inquiries%20associated%20with%20an%20anonymous%20session%20must%20have%20a%20session%20id,%20email%20and%20name.%20/%20Request%20failed:%20bad%20request%20(400)':!t,'undefined%20/%20Expected%20status%20code%20in%20(200-299),%20got%20400':!t,'undefined%20/%20Expected%20status%20code%20in%20(200-299),%20got%20404':!t,'undefined%20/%20Request%20failed:%20not%20found%20(404)':!t,'undefined%20/%20The%20Internet%20connection%20appears%20to%20be%20offline.':!t,'undefined%20/%20The%20request%20timed%20out.':!t),ms_values:!('undefined%20/%20Expected%20status%20code%20in%20(200-299),%20got%20404','undefined%20/%20Request%20failed:%20not%20found%20(404)','%20/%20Request%20failed:%20not%20found%20(404)','%20/%20The%20data%20couldn’t%20be%20read%20because%20it%20isn’t%20in%20the%20correct%20format.','undefined%20/%20Expected%20status%20code%20in%20(200-299),%20got%20400','undefined%20/%20The%20request%20timed%20out.','Inquirer%20cannot%20be%20an%20admin.%20/%20Request%20failed:%20bad%20request%20(400)','undefined%20/%20The%20Internet%20connection%20appears%20to%20be%20offline.','Inquiries%20associated%20with%20an%20anonymous%20session%20must%20have%20a%20session%20id,%20email%20and%20name.%20/%20Request%20failed:%20bad%20request%20(400)','%20/%20The%20Internet%20connection%20appears%20to%20be%20offline.','%20/%20The%20request%20timed%20out.','%20/%20The%20network%20connection%20was%20lost.'),segfilter:!((property:(name:response,source:properties,type:string),selected_property_type:string,type:string)),segment_type:string,subsegment_property:(name:errors,source:properties,type:string),subsegment_type:string,to_date:0,type:general,unit:day]

**Comment by alloy** [comment]
So those where we don’t receive any data are either because a network error occurred, the only thing we can do about that is ensure that we show a helpful message to the user, and the others are HTTP error statuses without a message.

E.g. a 404, which seems weird?

<img width="516" alt="screen shot 2015-12-09 at 12 13 31" src="https://cloud.githubusercontent.com/assets/2320/11683952/87432cce-9e6e-11e5-9fc3-ecc6711f1436.png">

----

[Here’s](https://mixpanel.com/report/275154/segmentation/#action:segment,arb_event:'Inquiry%20error',bool_op:and,chart_analysis_type:rolling,chart_type:line,from_date:-167,ms_checked:('%20/%20Request%20failed:%20not%20found%20(404)':!t,'%20/%20The%20Internet%20connection%20appears%20to%20be%20offline.':!f,'%20/%20The%20data%20couldn’t%20be%20read%20because%20it%20isn’t%20in%20the%20correct%20format.':!t,'%20/%20The%20network%20connection%20was%20lost.':!f,'%20/%20The%20request%20timed%20out.':!f,'Inquirer%20cannot%20be%20an%20admin.%20/%20Request%20failed:%20bad%20request%20(400)':!t,'Inquiries%20associated%20with%20an%20anonymous%20session%20must%20have%20a%20session%20id,%20email%20and%20name.%20/%20Request%20failed:%20bad%20request%20(400)':!t,'undefined%20/%20Expected%20status%20code%20in%20(200-299),%20got%20400':!t,'undefined%20/%20Expected%20status%20code%20in%20(200-299),%20got%20404':!t,'undefined%20/%20Request%20failed:%20not%20found%20(404)':!t,'undefined%20/%20The%20Internet%20connection%20appears%20to%20be%20offline.':!f,'undefined%20/%20The%20request%20timed%20out.':!f),ms_values:!('undefined%20/%20Expected%20status%20code%20in%20(200-299),%20got%20404','undefined%20/%20Request%20failed:%20not%20found%20(404)','%20/%20Request%20failed:%20not%20found%20(404)','%20/%20The%20data%20couldn’t%20be%20read%20because%20it%20isn’t%20in%20the%20correct%20format.','undefined%20/%20Expected%20status%20code%20in%20(200-299),%20got%20400','undefined%20/%20The%20request%20timed%20out.','Inquirer%20cannot%20be%20an%20admin.%20/%20Request%20failed:%20bad%20request%20(400)','undefined%20/%20The%20Internet%20connection%20appears%20to%20be%20offline.','Inquiries%20associated%20with%20an%20anonymous%20session%20must%20have%20a%20session%20id,%20email%20and%20name.%20/%20Request%20failed:%20bad%20request%20(400)','%20/%20The%20Internet%20connection%20appears%20to%20be%20offline.','%20/%20The%20request%20timed%20out.','%20/%20The%20network%20connection%20was%20lost.'),segfilter:!((property:(name:response,source:properties,type:string),selected_property_type:string,type:string)),segment_type:string,subsegment_property:(name:errors,source:properties,type:string),subsegment_type:string,to_date:0,type:general,unit:day) a view with all network errors removed.

@orta I was also wondering if this is from any app version or only certain versions? I couldn’t find where to specify that.

**Comment by orta** [comment]
[here](https://mixpanel.com/report/275154/segmentation/#action:segment,arb_event:'Inquiry%20error',bool_op:and,chart_analysis_type:rolling,chart_type:line,from_date:-167,ms_checked:('Request%20failed:%20not%20found%20(404)%20/%20':!t,'The%20Internet%20connection%20appears%20to%20be%20offline.%20/%20':!t),ms_values:!('Request%20failed:%20not%20found%20(404)%20/%20','The%20Internet%20connection%20appears%20to%20be%20offline.%20/%20'),segfilter:!((filter:(operand:!('2.3.2'),operator:%3D%3D),property:(name:'$app_version',source:properties,type:string),selected_property_type:string,type:string),(property:(name:errors,source:properties,type:string),selected_property_type:string,type:string)),segment_type:string,subsegment_property:(name:response,source:properties,type:string),subsegment_type:string,to_date:0,type:general,unit:day) is one specific to our latest release

**Comment by alloy** [comment]
Thanks!

So we use this [route](https://github.com/artsy/eigen/blob/5ecf46f9ec34738ad5e7e279c0b70b7997dff4e5/Artsy/Networking/ARNetworkConstants.m#L82). Looking at that endpoint, there are 2 explicit locations where a 404 is returned:

* [Artwork Not Found](https://github.com/artsy/gravity/blob/c0b34530922a7fcac2ff950cacab4da0728e632f/app/api/v1/me_artwork_inquiry_requests_endpoint.rb#L47)
* [User Not Found](https://github.com/artsy/gravity/blob/c0b34530922a7fcac2ff950cacab4da0728e632f/app/api/v1/me_artwork_inquiry_requests_endpoint.rb#L62)

However, both of these errors seem to include a message that would indicate what type the error is about, so not sure if us not having a response message means we’re doing something wrong when unpacking the error or if these are not the errors we’re looking for.

Maybe we should look at the Gravity logs for the corresponding calls?

**Comment by katarinabatina** [comment]
cc @anipetrov

**Comment by katarinabatina** [comment]
is this an issue we should keep open? @alloy

**Comment by alloy** [comment]
We’ve recently done an investigation into some inquiry issues, which is resolved. Right now there are no new errors being reported.
