### ISSUE TITLE
Remove "Ask a Specialist on 'not for sale'; 'sold'; 'on hold' works.

### ISSUE THREAD

**Issue by robertlenne** [artsy/eigen#857]
![image](https://cloud.githubusercontent.com/assets/566531/10321659/e0975e48-6c47-11e5-88f5-a999b1043156.png)

**Comment by alloy** [comment]
According to [the doc with rules](https://docs.google.com/document/d/1kQSHhCiFWxfVkSeql3GQA7UbBbhpNe-UyQ-c6q95Uq0/) we are doing the right thing, but it mentions being inconsistent across web versions as well, which is indeed the case:

* On Force it appears correct: https://www.artsy.net/artwork/richard-artschwager-mirror-slash-mirror-1
* On Martsy it shows both the ‘Ask a Specialist’ and ‘Price:’ label: https://m.artsy.net/artwork/richard-artschwager-mirror-slash-mirror-1

So need to check the logic that Force applies.

**Comment by robertlenne** [comment]
Related m.artsy issues: https://github.com/artsy/microgravity/issues/1095

**Comment by orta** [comment]
This is weird, we _only_ show this [if the](https://github.com/artsy/eigen/blob/master/Artsy/Views/Artwork/ARArtworkActionsView.m#L372) artwork is considered `inquirable` [by gravity](https://github.com/artsy/eigen/blob/c556eb5f126e2a9f36f2834e3139a2bc6a7e48b5/Artsy/Views/Artwork/ARArtworkActionsView.m#L200-L209). Shouldn't this fix come from the server?

/cc @craigspaeth 

I can obviously add checks for

**Comment by orta** [comment]
I talked with Joey about this in `#platform_humans`. Perhaps the fix is to have dynamic copy on martsy/eigen similar [to force](https://github.com/artsy/force/blob/690df2bfcedfcf9e6b720ec86514cb0865a2f6bd/models/artwork.coffee#L186-L191) which checks whether it can be actually bought and if not offers "Interested in related works? Chat with an Artsy specialist" as the copy for the inquire popup.
