### ISSUE TITLE
tap contact gallery button in microgravity, get pushed into eigen but get microgravity contact form

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#920]
visit microgravity artwork, tap contact gallery, get pushed into eigen with embedded microgravity inquiry form instead of native one.

**Comment by alloy** [comment]
I think this is similar to what @dzucconi has addressed here https://github.com/artsy/microgravity/issues/1136.

The issue being that it is redirecting the user to Force, which gets picked up as a Universal Links domain that Eigen claims. We can’t really do much about this in Eigen.

**Comment by katarinabatina** [comment]
@alloy sounds like Damon ran into some issues with the first solution he tried, is there anything else we can do on our end?

**Comment by alloy** [comment]
Yeah, the other solution, which I discussed with @dzucconi before, is to make Force accessible through another subdomain (e.g. `force.artsy.net`).

I talked that over with @craigspaeth not too long ago, we came to the conclusion that this probably didn’t work out when @dzucconi tried it because we apparently have a SSL certificate specifically for force/martsy.

However, that certificate will expire in February, so it might be worth it to spend some time to make force/martsy use the wildcard certificate as well and have `force.artsy.net` work, @craigspaeth?

**Comment by katarinabatina** [comment]
thanks @alloy! @craigspaeth thoughts? want to get a sense for when we might see a fix for this (or how we should prioritize against other things)

**Comment by craigspaeth** [comment]
So I believe @joeyAghion changed Force to the wildcard cert already. It shouldn't be too much more work to have Force running under `force.artsy.net`. I forget from our last conversation @alloy —is that all that's needed, and the rest of the work to leverage `force.artsy.net` is on Eigen?

**Comment by alloy** [comment]
@craigspaeth No the changes should be made in martsy. That's to say, everywhere martsy loads a Force URL, it should use the force subdomain so that Eigen won't capture it (it only does so for the m and www subdomains and the apex domain).

**Comment by katarinabatina** [comment]
@alloy @craigspaeth sorry to keep badgering here but I want to keep momentum on getting this fixed. Should I write up an issue in microgravity and have talk to .net about prioritizing?

**Comment by alloy** [comment]
@katarinabatina @craigspaeth Yes. Feel free to cc/invite me if there’s a need for me to explain the full situation once more.

**Comment by alloy** [comment]
Fixed by https://github.com/artsy/microgravity/issues/1213
